### ISSUE TITLE
[FR] Get channels in search results

### ISSUE THREAD

**Issue by KabbAmine** [ram-on/SkyTube#100]
I really like your app, good job.

Sometimes I can't remember the video's name but I remember the channel's name, so it will be great to get channels directly in the search results.

Is that hard to implement?

**Comment by ram-on** [comment]
It's already implemented.  All you need to do:

1. Search for the channel (by using the search box)
2. Videos related to that channel will appear.
3. Click on the bottom part of the video's cell as shown here:  http://i.imgur.com/F4YQ6uh.png

**Comment by KabbAmine** [comment]
Great, thanks.
