### ISSUE TITLE
[Bug]No new videos in feed tab

### ISSUE THREAD

**Issue by gtx155** [ram-on/SkyTube#101]
When i subscribe for some one it should show their recent videos but it doesnt.To fix this i unsub and sub again from the list of subs.I hope this will be fixed in the next update.The app is great tho

**Comment by ram-on** [comment]
> When i subscribe for some one it should show their recent videos but it doesnt

Can you pls reword it as I cannot understand your statement

**Comment by gtx155** [comment]
i subscribe for someone and go to feed tab and reload but there arent any videos from the channel  i subed for

**Comment by aykutkaraca** [comment]
If I am not wrong feed tab shows videos that are uploaded by the subscribed channel after the subscription date. Ram can correct me if I am wrong.

**Comment by ram-on** [comment]
@gtx155 Known issue - a design option limited by the number of usage in terms of the YouTube API Key.

To resolve it use your own YouTube API key.  The key can be inputted by going to Preferences > Others > YouTube API Key.
