### ISSUE TITLE
[Bug]Info button

### ISSUE THREAD

**Issue by gtx155** [ram-on/SkyTube#102]
When i press the info button in a video it takes the whole screen and can not be closed.Hope this will be fixed in the next update.

**Comment by ram-on** [comment]
Pls submit a screenshot of what happens when you click on the info button (as mine works great).

**Comment by gtx155** [comment]
https://i.imgur.com/2BSeA8S.jpg

**Comment by ram-on** [comment]
@gtx155 You have a very low resolution phone is assume, correct?

**Comment by gtx155** [comment]
yes

**Comment by ram-on** [comment]
Fixed as per b9df27a523089ada3e45e4c5e25e9a002c666ea9.
