### ISSUE TITLE
[Bug] Change in screen orientation causes SkyTube to crash

### ISSUE THREAD

**Issue by github-throwaway** [ram-on/SkyTube#103]
This happens in two scenarios:

1. While browsing SkyTube a change in screen orientation will instantly cause a crash of the app.

2. If a change in screen orientation occurs while watching a video, the app will crash once you either use the back arrow in the top left corner or the back button. However, switching the orientation back and forth while playing a video won't cause a crash.

This error does not occur on SkyTube 2.4 Extra.

**N9005 | Android 5.0 | SkyTube 2.4**

**Comment by ram-on** [comment]
Hello @github-throwaway 

I fixed that issue at commit d3a0babce5f0f041d0a253e867e5e754f58e477a.  For some reason, F-Droid did not capture it...  If you can't tolerate such crashes, then switch to SkyTube Extra.

In any case, I shall push the next release for this weekend and this will be resolved.

**Comment by ram-on** [comment]
Released v2.41.  This issue should be resolved.  Thanks 4 reporting.
