### ISSUE TITLE
Subscription feed not showing videos

### ISSUE THREAD

**Issue by 1lk** [ram-on/SkyTube#105]
Hello! I added the youtube data api key but the subscriptions feed doesn't display anything (says I don't have any subscriptions). How can this be fixed?

**Comment by aykutkaraca** [comment]
Have you subscribed to any channel?

**Comment by 1lk** [comment]
Yes, I have. Actually 865 subscriptions. The API also seem to show it's pulling requests http://i.imgur.com/7ANMLAy.png but no data is going back?

**Comment by ram-on** [comment]
@1lk I've entered a custom key and I can still retrieve the subscriptions and the feed.

Can you please attach the ADB log?

**Comment by ram-on** [comment]
Closed the issue due to the lack of feedback.
