### ISSUE TITLE
Won't request permissions, Nougat  ( Full Net access) 

### ISSUE THREAD

**Issue by poppypundit** [ram-on/SkyTube#108]
It won't ask permissions, Hence it doest connect to internet services, Wi-Fi nor Data. Running Lineage OS, 7.1.2 in LG G3.

**Comment by ram-on** [comment]
Hello, I've tested it on stock Android 7.1.1 and it works great.

Can you please describe what is not working?

**Comment by poppypundit** [comment]
Featured, Most popular, Feeds etc...nothing loads. It wont let me search for videos either. When I checked the "app info" under settings, permissions tab for the app is greyed out. I wasn't asked for net access either. 

It works great on KitKat. I don't use a YouTube app API on either device. 

Thanks for the app. I really love it!

**Comment by poppypundit** [comment]
Suddenly working now! Huge surprise, not sure what happened. Sorry for the trouble! Closing this issue. Permissions are still greyed out though!
