### ISSUE TITLE
[Request] Swipe controls

### ISSUE THREAD

**Issue by Generator** [ram-on/SkyTube#109]
Add swipe controls to Volume, Seek and Brightness, like on some other players (VLC, NewPipe).

Noting wrong with onscreen controls, but swipe can be useful and fluid, could be optional (not enabled by default).
Also ability do select what controls to use (onscreen, disable Volume, Seek or Brightness swipe control)

**Comment by avently** [comment]
@ram-on,
This is a really useful feature. Because for now its not easy to rewind (long videos is terrible). Mxplayer has a great example of this feature. Maybe you can use the same behaviour.

**Comment by avently** [comment]
@ram-on
Here is android sources with this functionality:

This is activity where user has access to media controls:  
https://github.com/LineageOS/android_packages_apps_Gallery2/blob/cm-14.1/src/com/android/gallery3d/app/MoviePlayer.java

Overlay view:
https://github.com/LineageOS/android_packages_apps_Gallery2/blob/cm-14.1/src/com/android/gallery3d/app/GestureControllerOverlay.java

Gestures controller:
https://github.com/LineageOS/android_packages_apps_Gallery2/blob/cm-14.1/src/com/android/gallery3d/app/GestureController.java


Is it enough for you or i should find another source of that functionality?

**Comment by ram-on** [comment]
Thanks for the source reference.  I'll take a look into it later on.  Are you familiar with java?  If yes I'll appreciate if you contribute to implement this feature.

**Comment by avently** [comment]
@ram-on 
I'm not familiar with Java.

**Comment by avently** [comment]
@ram-on hello.
I made swipe controls and background playback (made it better than my previous implementation).
Please, check this out and tell what do your think about it. Will you merge this features or not.
APK is located inside the archive.
[skytube.zip](https://github.com/ram-on/SkyTube/files/1370120/skytube.zip)

**Comment by Generator** [comment]
Just tested that version by @avently and look great, no major issues, only the options missing (enable/disable swipe controls or witch controls [Volume, Brightness, Seek]).

**Comment by avently** [comment]
@Generator feel free to use my fork of SkyTube with new features added. You can build it yourself and no need to trust my apk:)
https://github.com/avently/skytube

**Comment by ildar** [comment]
@ram-on , would you merge this functionality if properly implemented?

**Comment by ram-on** [comment]
Swipe control implemented as per 00cbe595935959c79d4775a18aaeca1eca8c10e4.
