### ISSUE TITLE
Paste youtube/youtu.be links

### ISSUE THREAD

**Issue by goldencut** [ram-on/SkyTube#11]
Would be nice to be able paste youtube video, maybe even playlist http links in ST.

**Comment by ram-on** [comment]
Done.

**Comment by goldencut** [comment]
Awesome, will it be pushed to F-Droid?

**Comment by ram-on** [comment]
Probably next weekend or so.

**Comment by goldencut** [comment]
Thanks, nice to see things progressing. Although, the sudden jump in file size is somewhat disconcerting.. :P
One problem that I noticed is that the search box gets cleared every time user goes back from search results. Often they just want to refine the search but now they have to type the whole search string again. Maybe keep the search string and add 'x' to the end of search box to clear it quickly?

BR,
G

**Comment by ram-on** [comment]
> Although, the sudden jump in file size is somewhat disconcerting.

This is because I'm now using the appcompat Android library (mainly because of the subscriptions menu + material theme)

> One problem that I noticed is that the search box gets cleared every time user goes back from search results. Often they just want to refine the search but now they have to type the whole search string again. Maybe keep the search string and add 'x' to the end of search box to clear it quickly?

Please open a new thread/issue so that I can keep track of this feature request.
