### ISSUE TITLE
Immersive mode video player

### ISSUE THREAD

**Issue by baskervald** [ram-on/SkyTube#117]
Trying out SkyTube right now since I've been wanting to get away from the default player for ages and I love it so far, but actually having the video full screen so you don't have to see the navigation bar when watching the video would put the icing on the cake. Also possibly the ability to hide the info and comments icons that overlay on the top right and bottom left corners of the video would be incredibly appreciated.

**Comment by baskervald** [comment]
At first using the actual YouTube player seems like a solution, but then you aren't able to open the comments nor the video information, which is an important part of navigation.

**Comment by ram-on** [comment]
Identical to issue #40.  However I'll leave your request open as I like your wording (i.e. immersive mode).  I'll put such option in the preferences/settings.

**Comment by ram-on** [comment]
FR has now been implemented.  Refer to 69f2a2a6b7a2df530e875aa6872e6b33364a6820:   YouTube player will, from now on, hide the comments and video description icons after a couple of seconds after the HUD is hidden. An option is now implemented in the preferences to disable this behavior (immersive mode).
