### ISSUE TITLE
Rules to use the code

### ISSUE THREAD

**Issue by aykutkaraca** [ram-on/SkyTube#119]
Hi Ram-on,

I delightfully use your skytube. This isn't an issue but a question. I am new on github so if it isn't the right place I am sorry.

What are the rules to use your code for building another app based on skytube? It can be free with ads or for paid app. Can I use your code and modify it?

Thanks in advance,
Aykut

**Comment by ram-on** [comment]
> It can be free with ads or for paid app. Can I use your code and modify it?

You can distribute the app with ads provided that the source code remains open-source and available to users.  These are the terms of the GNU General Public License (version 3.0).
