### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by alex9434** [ram-on/SkyTube#12]
I really like the SkyTube app. Thank you very much for your work! However, it quickly drains my battery and my tab (Samsung Galaxy Tab 2 10.1) gets hot. VLC is able to use hardware acceleration that uses significantly less battery and keeps the device cool. Is it possible to use the video engine from VLC for SkyTube?

**Comment by ram-on** [comment]
Good point.  I'll enable [hardware acceleration](https://developer.android.com/guide/topics/graphics/hardware-accel.html) for the next release.

**Comment by ram-on** [comment]
Done.

**Comment by alex9434** [comment]
great, thanks!
