### ISSUE TITLE
Feature Request: Subscription Import/Export/Sync

### ISSUE THREAD

**Issue by NotAFile** [ram-on/SkyTube#126]
Self explanitory.

Ideally, it could parse the data from Google Takeout too.

**Comment by ram-on** [comment]
Basically you want your subscriptions to be synchronized across your devices, right?

**Comment by NotAFile** [comment]
Well that might be the end goal, but for now small steps. I currently can't use skytube because I would have to add my ~100 subscriptions manually.

Having some way of importing and exporting would help a lot with that.

**Comment by ram-on** [comment]
Importing and exporting feature has just been implemented and is part of version 2.60.

To import/export, go to Preferences > Backups.

**Comment by NotAFile** [comment]
Oh, great, I had no idea. That update is actually what reminded me skytube exists and promted me to write this feature request :D
