### ISSUE TITLE
Option to set Landscape or Portrait mode for video play

### ISSUE THREAD

**Issue by waqas** [ram-on/SkyTube#13]
I keep screen rotation off almost all the time and I guess many folks do the same. So it is kinda weird to watch video in Portrait mode or turn on rotation which changes the whole phone's UI. It would be great if an option is available to always play video in Landscape mode. Just like there is an option for video quality.

Thanks.

**Comment by ram-on** [comment]
Resolved as per commit 43826527cfbfc0d882e1bb8d2a8f12003ed10f0b.
