### ISSUE TITLE
[BUG] Failed to reproduce video

### ISSUE THREAD

**Issue by Generator** [ram-on/SkyTube#131]
I've encounter this message several times, when opening a video some times fails to reproduce the video with the message "Can't play this video", need to tap OK and reload the video (with reload icon on top screen) til the video opens
![screenshot_20170714-010404](https://user-images.githubusercontent.com/44146/28192942-4c6a2bb4-6831-11e7-9634-74a5ef891ed6.png)

**Skytube:** 2.60 [F-Droid]
**ROM:** AOSP Extended 4.4 [Android 7.1.2]

**Logcat:**
[skytube.log.gz](https://github.com/ram-on/SkyTube/files/1146983/skytube.log.gz)

**Comment by ram-on** [comment]
Can you pls indicate which video you were trying to play?  (I'll analyze the log later on).

**Comment by ram-on** [comment]
Closing this due to lack of feedback.
