### ISSUE TITLE
HTML entities in french translation lead to build errors

### ISSUE THREAD

**Issue by I-Al-Istannen** [ram-on/SkyTube#139]
I dearly hope this is not just me, but the history suggests it was an error earlier too?
Also, I saw no default format for issues, so I hope this is okay :)

**Problem:**
Building the project fails with e.g. this error:
```
Error: (4, 35) Error: Entity "eacute" was referenced but not declared
Error: Execution failed for task ':app:mergeExtraDebugResources'.
```
This happens because these HTML entities are sadly no XML ones and not defined either.

**Solution:**
Just replacing them with the literal character should work, otherwise you can properly escape them.

<br/>
<br/>

**Unrelated:**  
Is there any place I can ask for help building this? It seems to error a few times, additional to that.
```
Package not included in Android
../../../../../../.gradle/caches/modules-2/files-2.1/org.mozilla/rhino/1.7.7/3a9ea863b86126b0ed8f2fe2230412747cd3c254/rhino-1.7.7.jar: Invalid package reference in library; not included in Android: java.awt.event. Referenced from org.mozilla.javascript.tools.debugger.ContextWindow.
```

```
Appcompat Custom Widgets
../../src/main/java/free/rm/skytube/gui/businessobjects/SubscribeButton.java:31: This custom view should extend android.support.v7.widget.AppCompatButton instead
```

**Comment by ram-on** [comment]
@I-Al-Istannen Thx for reporting this bug.  It has now been fixed - 3b92c379ba4abadcba0f05d8b071e2feb735d5e9.

@RemyL For future contributions, please do not use HTML codes (such as `&eacute;` or `&agrave;` ...etc) - use the actual characters instead (i.e. é or à ...etc).

@I-Al-Istannen regarding that error, try to clean the project (using Build > Clean Project) - although, to be honest, I've never encountered that error before.
