### ISSUE TITLE
Error:(23, 48) error: package org.schabi.newpipe.extractor.stream_info does not exist

### ISSUE THREAD

**Issue by jxamen** [ram-on/SkyTube#140]
Error:(23, 48) error: package org.schabi.newpipe.extractor.stream_info does not exist
Error:(28, 36) error: package org.schabi.newpipe.extractor does not exist

help me...

**Comment by ram-on** [comment]
```bash
cd app/src/main/java/org/schabi/newpipe/
git clone https://github.com/ram-on/extractor.git
```
