### ISSUE TITLE
[Bug] Multi-window breaks video player

### ISSUE THREAD

**Issue by AffeAli** [ram-on/SkyTube#141]
If you (de)activate the Android Nougat multi-window feature while a video is playing, the video player stops working.
Screenshot: ![screenshot_20170810-003857](https://user-images.githubusercontent.com/20579579/29486560-5704c9f6-84e9-11e7-8928-ca2ae8dc053b.png)

**Comment by ram-on** [comment]
Issue appears to be resolved now.
