### ISSUE TITLE
(FR) Control buttons not hidden

### ISSUE THREAD

**Issue by OmlineEditor** [ram-on/SkyTube#142]
When playing in full screen, the device control buttons are **not hidden**. Buttons are always shown, this prevents.
( Android 6.0 / Lenovo Tab 3 Plus )

![trending](https://user-images.githubusercontent.com/13348933/29532468-fe3a455c-86b5-11e7-8770-4736d080fc99.jpg)

**Comment by ram-on** [comment]
Hi, this is not a bug - it works as intended (i.e. controls button are always visible).

I'm placing this as feature request.

**Comment by OmlineEditor** [comment]
Please make sure that the buttons can be hidden. When the buttons on the screen are not convenient they interfere. Make the settings so that you can hide or leave them on the screen

**Comment by ram-on** [comment]
Implemented.  Refer to 6b8f2e48d4e038e2d97e1c9f8ae1a745475af006.
