### ISSUE TITLE
HTTP Streaming of MP4 files

### ISSUE THREAD

**Issue by ronlinet** [ram-on/SkyTube#144]
I would like to reuse this code to stream mp4 files harvested from a JSON web page. 
Is the the mp4 streaming already inbuilt in the app, if not would it take a lot to refactor the code?

**Comment by ram-on** [comment]
Hi, sorry for the late reply.  Currently the code downloads a stream (either a MP4 or WEBM) and the stream is displayed via a video view.

**Comment by ronlinet** [comment]
Thank your for the feedback @ram-on , I will close this and open another one if I will any other advise regarding this.
