### ISSUE TITLE
Copies on the Play Store

### ISSUE THREAD

**Issue by Poussinou** [ram-on/SkyTube#145]
Hi @ram-on,
I found many copies of Sky-Tube on the Play Store : 
* https://play.google.com/store/apps/details?id=free.rm.rextube.extra
* https://play.google.com/store/apps/details?id=com.farmaapps.tubezsd
* https://play.google.com/store/apps/details?id=com.laughingvideo

They claim to be based on SkyTube (that's right)  but they do not respect the GNU GPL v3, and two of them are basically your app but with ads in it...

As you are the owner of the source code, you can report them [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay), if it's your wish !

**Comment by ram-on** [comment]
Thanks for the tip of.  I'll shall report them due to a breach to the GPLv3.

**Comment by ronlinet** [comment]
@ram-on  I am evaluating this app and if it fits the requirements I may consider to use it for further industrial purposes.  
I am willing to financially contribute to your project in exchange for a more permissive license ( MIT, WTFPL ? ). 
Apologies for  hijacking this topic but there is no way to message to a user through a github. Is there any way to get in touch by email? 
Regards,

**Comment by ram-on** [comment]
@ronlinet Send me email @ https://i.imgur.com/FAkgAL1.png

**Comment by ram-on** [comment]
@Poussinou The above apps were reported.  Once again, thank you.
