### ISSUE TITLE
import subscribed channel from YouTube account

### ISSUE THREAD

**Issue by juanserj45** [ram-on/SkyTube#148]
Hey your app is great but I tried searching a way to import my list of channels from YouTube to your app but I can't, is there a way to do that or only manually? Maybe you can add keywords to make new recommendations of videos or channel in keywords chosen by the user. Thx

**Comment by atomjack** [comment]
This is actually something I've worked on but haven't pushed up here yet. I'll try to take another look at it and make a PR for @ram-on to take a look at.

**Comment by ram-on** [comment]
@juanserj45 YouTube subscriptions importation feature will be available in the next release.

**Comment by juanserj45** [comment]
@ram-on  thx keep with your hard work

**Comment by ram-on** [comment]
Feature implemented - refer to b601d07abbd531c6b9972912347ea2c88b2fed82
