### ISSUE TITLE
360p being mistaken as 480p

### ISSUE THREAD

**Issue by switchtegrax1** [ram-on/SkyTube#150]
Whenever i select 360p it plays 480p videos i found it out as some 480p videos do play on my low end phone and changing between 360-480p produces the same results as above (some play slowly but most just keep loading) Also both 360-480p produce the same video quality just to make it clear.

**Comment by ram-on** [comment]
For some reason, the app is not retrieving 480p video URLs and as a result it is always playing in 360p.

**Comment by switchtegrax1** [comment]
its actually the oposite ,it can't retrieve 360p urls so it always plays 480p videos

**Comment by ram-on** [comment]
This issue should be resolved by now due to recent updates to the extractor library.
