### ISSUE TITLE
Subscribing to channel from YouTubePlayer doesn't add videos to Feed db

### ISSUE THREAD

**Issue by atomjack** [ram-on/SkyTube#153]
When you view a video from a channel that you are not subscribed to, and pull up the video description and hit the Subscribe button, that channel's videos are not added to the Feed database.

In fact, if you've already got subscriptions, the only videos from the newly subscribed channel that will ever show up in the Feed tab are ones that were published after you subscribed to it (since it doesn't fetch any videos published after the last time you updated the Feed tab).

I'd like to fix this, and I propose adding some functionality into the `SubscribeButton` class that handles subscribing to the channel, and fetching videos from the channel and saving them to the database (utilizing existing code of course). Specifically, instead of having to set the onClickListener each time you use the button, we can have the button set it itself, to launch a new `SubscribeToChannelTask`, as well as launching another task to fetch the channel's videos and save them to the feed db. 

`ChannelBrowserFragment` also saves the videos from the video grid to the database when the click happens, so I will also have a flag that can be set to have the Button not launch the second task that fetches the channel's videos.

My almost-done Chromecast branch uses the SubscribeButton (in fact it uses the video_description layout xml) so it makes sense to me to do it this way.

Let me know what you think.

**Comment by ram-on** [comment]
I agree with putting such code into the SubscribeButton such that such code is shared by both ChannelBrowserFragment and YouTubePlayerFragment.

**Comment by ram-on** [comment]
Fixed as per 5a17bbe5f618e2fcc0ffc24b048860d578ad6d8e
