### ISSUE TITLE
Unable to run project from latest commits

### ISSUE THREAD

**Issue by RikNorakomi** [ram-on/SkyTube#158]
Would love to try out this project and dig into it deeper.
But trying to run it from Android Studio gives me a bunch of errors telling me packages and classes cannot be found.
Could anyone get me up to speed on how to get the project running?

`/Users/rikvanvelzen/AndroidStudioProjects/YoutubeRelated/SkyTube/app/src/main/java/free/rm/skytube/businessobjects/VideoStream/StreamMetaData.java
/Users/rikvanvelzen/AndroidStudioProjects/YoutubeRelated/SkyTube/app/src/main/java/free/rm/skytube/businessobjects/VideoStream/HttpDownloader.java
Error:(47, 24) error: cannot find symbol class VideoStream
Error:(23, 43) error: package org.schabi.newpipe.extractor.stream does not exist
Error:(28, 36) error: package org.schabi.newpipe.extractor does not exist
Error:(29, 47) error: package org.schabi.newpipe.extractor.exceptions does not exist
Error:(52, 78) error: cannot find symbol class ReCaptchaException
Error:(31, 36) error: package org.schabi.newpipe.extractor does not exist
/Users/rikvanvelzen/AndroidStudioProjects/YoutubeRelated/SkyTube/app/src/main/java/free/rm/skytube/businessobjects/VideoStream/ParseStreamMetaData.java
Error:(45, 40) error: cannot find symbol class Downloader
Error:(30, 36) error: package org.schabi.newpipe.extractor does not exist
Error:(98, 61) error: cannot find symbol class ReCaptchaException
Error:(59, 99) error: cannot find symbol class ReCaptchaException
Error:(33, 43) error: package org.schabi.newpipe.extractor.stream does not exist
Error:(34, 43) error: package org.schabi.newpipe.extractor.stream does not exist
Error:Execution failed for task ':app:compileOssDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Error:(35, 43) error: package org.schabi.newpipe.extractor.stream does not exist
Error:(32, 47) error: package org.schabi.newpipe.extractor.exceptions does not exist`

**Comment by ram-on** [comment]
```
cd app/src/main/java/org/schabi/newpipe
git clone https://github.com/ram-on/extractor.git
```
