### ISSUE TITLE
Keep history on search string

### ISSUE THREAD

**Issue by mcitew** [ram-on/SkyTube#163]
Maybe request that the search string be remembered, maybe maximum of 50 strings, if overflows it can push out the old and less popular search, or something scheme.

**Comment by ram-on** [comment]
Will be implemented.  I'm closing this as it is duplicate to #57

**Comment by mcitew** [comment]
Bookmark is not the same as keeping history of search string.

Keep history search string is to east re enter the new search or modifying the video search.

Bookmark is to keep a record of searched video. 

I don't see how the bookmark feature solves this issue.

**Comment by atomjack** [comment]
I just added this feature, how's this look? You can also delete the entries with the X button.

![screenshot_20180103-132800](https://user-images.githubusercontent.com/114672/34540659-3800edac-f08a-11e7-9394-00296a0a22d7.png)

**Comment by ram-on** [comment]
@atomjack Hey Chris, it looks great.  Just add an option in the preferences to not record search history.

**Comment by atomjack** [comment]
@ram-on Cool, should that be off by default? As in, it will record search history by default?

**Comment by ram-on** [comment]
> it will record search history by default?

Yes pls

**Comment by atomjack** [comment]
Done. When you check the box to disable it, it will clear the Search History Database.

**Comment by ram-on** [comment]
Implemented as per 8029882522cad25dfe6c09826899dfa481a5eca0
