### ISSUE TITLE
Difficult to navigate video items using IR remote ( on android tv )

### ISSUE THREAD

**Issue by mcitew** [ram-on/SkyTube#164]
The app when loaded on android TV box works. However, it is cumbersome because it requires to put the IR remote into 'mouse mode' and must press and hold the up/down/left/right keys for a long time to navigate to the next video item. On TV the screen is big, so it is very tiresome to move selection this way.

The app should allow keyboard up/down/left/right keys to be used to jump from one video item to the next. This will improve significantly the user-friendliness of the app when running on android TV.

**Comment by ram-on** [comment]
This will be implemented in the near future.  Closing this FR as it is duplicate to #20
