### ISSUE TITLE
Youtu.be links error out

### ISSUE THREAD

**Issue by goldencut** [ram-on/SkyTube#17]
Pasting links like https://youtu.be/TjJIhW0GdyQ gives: an error has occured while getting video streams for...

**Comment by goldencut** [comment]
I stand corrected, it's not the pasting - most videos won't play and give that error.

**Comment by ram-on** [comment]
99% sure this issue is related to #7.

If you have access to `adb`, please dump down the contents of `adb log` and submit it to me as I cannot replicate that issue (i.e. the above link works perfectly on my devices).

**Comment by goldencut** [comment]
Have to see if the distro I have as a backup OS has adb available. Might take a few days or so.

**Comment by ram-on** [comment]
No feedback given & cannot replicate the issue.  Closing it for now.
