### ISSUE TITLE
Audio stops randomly

### ISSUE THREAD

**Issue by Dixon-Jose** [ram-on/SkyTube#173]
When  watching a video the audio stops randomly but the video keeps on playing. This keeps happening quite often, quick fix is to seek backwards. But even though the video is buffered which i am sure is, takes long time to seek.

**Comment by ram-on** [comment]
@Dixon-Jose Can you kindly try out the Beta and see if this issue persists?  Beta is located at #166 (refer to the last post).

**Comment by Dixon-Jose** [comment]
@ram-on I used the beta version SkyTube-Extra-2.691Beta.apk.zip from #166 . Worked fine for the first few hours, then it happened again.
First the audio goes off and video plays for a few seconds and whole thing comes to a stop until you reload it, which then skips forward the video a couple of seconds.
The other issue that comes after this is, no other video plays.When you click the video, the audio plays and on screen it displays "the video can't be played" while the audio is being played in the background.Only way i found to work around is to reboot android.

**Comment by ram-on** [comment]
Can you indicate the Operating System version and what device are you using?

Also are you using a similar network configuration like issue #168?

**Comment by Dixon-Jose** [comment]
No i'm not using similar network configuration like #168  and in terms of operating system i'm following [https://download.lineageos.org/bacon](url) builds. Could it be the cause ?
also this doesn't happen in short videos rather in videos of length more than 20 min, if that helps.

**Comment by ram-on** [comment]
It could be as Lineageos is still hasn't been officially released yet.
