### ISSUE TITLE
About privacy

### ISSUE THREAD

**Issue by stemy2** [ram-on/SkyTube#179]
Hello,

In the description, i can see «Not dependent on the GAPPS/Google Apps (i.e. YouTube official app),no need for Google/YouTube account to operate, my code does not spy on your behaviour!».

It means that your app dosn't spy anyone, but does it means that it prevents google to do so ?

Thanks.

**Comment by ram-on** [comment]
Google owns the Android OS.  SkyTube have no control on what Android does with the data is processes.  That statement means that SkyTube's OSS code does not try to learn what videos you like ...etc.
