### ISSUE TITLE
Top bar while viewing video not clickable

### ISSUE THREAD

**Issue by ByteTemplar** [ram-on/SkyTube#180]
I have odd problem on latest version. I cant click any of the actions on top bar when viewing video (three dots, reload? and back). Bottom bar controls work, sidebar comments work, but I cant use top bar functions at all. This is very bad, cause I cant share videos anymore, cause the option was removed from list view.

Any chance adding it back or maybe find a reason why I cant use the top bar?

I was using the older version till recently it started to act up and upgraded...

**Comment by ram-on** [comment]
@ByteTemplar I've just released a new version of SkyTube (2.70).  Can you try it out and check whether you are still experiencing this issue?

**Comment by ByteTemplar** [comment]
Oh nice, will report back when F-droid has the update available!

**Comment by ByteTemplar** [comment]
Ok, updated to 2.70 and still cant click anything on top bar. But now that you returned the same functions on list view, I can share videos again there. So basicly my problem is "solved".

I really dont know why it wont register the top bar buttons. I even activated in developer settings the option that it shows touches on screen, and the touches are visible on top bar and thus working physically, but software wont do nothing...

**Comment by ram-on** [comment]
@ByteTemplar That's very strange.  What Operating System and device are you using?

**Comment by ByteTemplar** [comment]
Its oldie but works fine otherwise, tablet is Pipo P9 and its running KitKat 4.4.2. Unfortunately its been abandoned by manufacturer long time ago, but hardware is still amazing and runs everything no problems. I use it mostly on streaming media anymore...

**Comment by ram-on** [comment]
I'm still using Android 4.4.* however I cannot replicate that issue.  I'm assuming that the top bar of other apps works great, right?

**Comment by ByteTemplar** [comment]
Yeah, no other app has that problem that Im using, like for example this web browser Im using to reply and its tab work fine on top of screen on same spot.

But its not a huge problem anymore cause now I can share videos from list screen again, cause you returned that option in 2.70! So Im fine closing this issue tbh, its a really weird glitch :)

**Comment by ram-on** [comment]
Very weird indeed.  I have to close this issue as unfortunately I cannot replicate this issue, even when I'm using the Android's emulator.  Sorry about that!
