### ISSUE TITLE
Missing old videos in channel

### ISSUE THREAD

**Issue by ypms** [ram-on/SkyTube#182]
Look at this screenshot:

![1](https://user-images.githubusercontent.com/33480632/32541519-e67e9db2-c43d-11e7-987b-a8dad8fff3c9.png)

According this, here no more videos at this channel at all. But in search I able to find more old videos:

![4](https://user-images.githubusercontent.com/33480632/32541588-133f9018-c43e-11e7-8f81-64b28319dbbc.png)

I'am using latest version 2.60 from F-Droid.

**Comment by ram-on** [comment]
Hi @ypms.  This is a known design issue which we had to make in order not to exeed the YouTube API's quota limit.  This can be solved by going to Preference > Others > and input your YouTube API Key.
