### ISSUE TITLE
Incorrent message "disabled comments"

### ISSUE THREAD

**Issue by ypms** [ram-on/SkyTube#183]
![2](https://user-images.githubusercontent.com/33480632/32541643-465e3788-c43e-11e7-9e0e-e792c73d7e4d.png)

Occured for example, when connection lost. Change to proper message.

**Comment by ram-on** [comment]
Can you indicate the steps to replicate this bug?

**Comment by ram-on** [comment]
I'm closing this issue as no further feedback was received.  Feel free to reopen it.
