### ISSUE TITLE
Get back button for sharing video to lists

### ISSUE THREAD

**Issue by ypms** [ram-on/SkyTube#184]
Currently if I want to share video, I must open video, wait loading, swipe this little button and only after it I can copy/share link. This is totally insane and PAIN for me, when I want share many links.

![3](https://user-images.githubusercontent.com/33480632/32541695-78459ca0-c43e-11e7-8718-d6cbbf52dc22.png)

Get back a little button, which was in earlier versions:

![5](https://user-images.githubusercontent.com/33480632/32541780-c0e0cc14-c43e-11e7-9a7c-482d1a0f3d4b.png)
 
I very loved this button. But key in older version is expired.

I'am using latest version 2.60 from F-Droid.

**Comment by ram-on** [comment]
This has been solved in version 2.70.  I've released it and it should be soon available @ F-Droid.
