### ISSUE TITLE
Totally empty channels

### ISSUE THREAD

**Issue by ypms** [ram-on/SkyTube#185]
For example, if I use search, I can to find and view video:

![6](https://user-images.githubusercontent.com/33480632/32541882-f83dd0da-c43e-11e7-8d0f-ad6b55020c20.png)

But if I go to channel, I see totally empty channel:

![7](https://user-images.githubusercontent.com/33480632/32541925-1d54b7f8-c43f-11e7-8cde-7c38314db94f.png)

This channel have many videos and I can watch it in browser:

![8](https://user-images.githubusercontent.com/33480632/32541957-3062b444-c43f-11e7-8867-959efe5df0c6.png)

I'am using latest version 2.60 from F-Droid.

**Comment by ram-on** [comment]
As noted in #182, This is a known design issue which we had to make in order not to exeed the YouTube API's quota limit. This can be solved by going to Preference > Others > and input your YouTube API Key.
