### ISSUE TITLE
Add Playlist feature

### ISSUE THREAD

**Issue by ypms** [ram-on/SkyTube#186]
Some channels have only playlists and updating only it. One example with many subscribers and large playlist:

![9](https://user-images.githubusercontent.com/33480632/32542026-6676ea32-c43f-11e7-9ddf-df8f12914843.png)

**Comment by atomjack** [comment]
I actually just pushed up a branch that adds Channel Playlist support. I imagine it should be ready soon but it's up to @ram-on.

**Comment by ram-on** [comment]
Playlist is now supported by SkyTube as per @atomjack's PR (#190 and 3617c83058c87bb12af98b447e850df8c1517643).  It will be available in the next release.
