### ISSUE TITLE
App very slow to sync/update new videos

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ram-on/SkyTube#195]
Hi,

I notice that my SkyTube app in version 2.70 from FDroid on Lineage OS is really slow to update the new videos that have been published. I get the popup stating that it is updating (although clicking around this popup allows me to browse and watch videos while it is updating) and it can take about 2-3 minutes to finish, every time. I have a bit less than 400 channel to sync but still, it's instant on the official app so there must be a problem.
I don't know if this is a recent issue as it's the first version i have been using (and so far, i am very pleased :) )

Don't hesitate to ask me for more information. Otherwise great work so far

(btw, newpipe is open source too and has a ... way better player than SkyTube, I really think you should take theirs :p )

**Comment by thiswillbeyourgithub** [comment]
I have a feeling it might be caused by your app unintentionally syncing twice at the same time. I sometimes get two popular stating that no videos were added, things like that

**Comment by ram-on** [comment]
@thiswillbeyourgithub pls list down the steps needed to show such popup twice.

**Comment by thiswillbeyourgithub** [comment]
Okay, thanks :)

So, first thing : i just launched the app and refreshed the feed. I get the loading popup and after the long (2-3minutes long..) wait it disappears and another "loading popup" stays on screen : it was actually beneath and stays on. I let it run for maybe 4 minutes and it didn't budge (stuck at 0 channel checked, althouth there is the loading circle animation thing going on). I can press the backbutton and enjoy the refreshed feed but still, it's odd.

Second thing : I noticed that if I try to refresh the feed, wait one second for the loading popup to appear then press the back button :  the loading popup disappears, allowing me to watch a memorized video while the sync refreshes (remember : several minutes to wait). But when I do this I am notified that the refresh is done via this very small popup at the bottom of the screen. I am fairly certain that I have had it two times in a row at times but I can't seem to reproduce it at the moment. I'll get back to you here if I figure it out.

Don't hesitate to ask me for clarifications.

Thank you again for caring, your app rocks already :)

**Comment by Tvax** [comment]
I experience the same issue, it takes time to get the channels to be checked for new videos.
I'm also on LOS, but it was as long to check for new videos as it is right now when I was on my stock ROM

**Comment by ram-on** [comment]
Due to commits 214e993cd9c096cffb6ccae40d1e874dd11c68f9 and b3cc1489bb7add86c492327ed423cb961ee61dd4, the feed refreshing process should be performed much faster (around 70% faster).

The refreshing process of 300+ channels is now performed under 20 seconds on my device.
