### ISSUE TITLE
[FR] search history

### ISSUE THREAD

**Issue by ildar** [ram-on/SkyTube#2]
Would be great to have the search history independent from YouTube accounts..

**Comment by ode79** [comment]
This would be great improvement.

Even just session history would be very useful.

I've found when I search for something and it's not quite right I tap back and then have to type the whole phrase again and modify it slightly rather than just modify what the search box remembers from the last search.

**Comment by ildar** [comment]
I see "Subscriptions" added. That's nice!
I wonder if it's possible to add "subscriptions" for search results? Then
it'd satisfy this feature request (mostly).
Thanks!

**Comment by ram-on** [comment]
> I wonder if it's possible to add "subscriptions" for search results

Please explain.

**Comment by ildar** [comment]
A "subscription" in the app isn't a real YT thing tied to an account. It's
just a link to a YT page (the channel page particularly). So can't we have
a link to other types of pages?
E.g. in WebTube you can do exactly that: "Star" any page whether it's a
channel, a video or a search result.

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by ram-on** [comment]
> A "subscription" in the app isn't a real YT thing tied to an account. It's just a link to a YT page (the channel page particularly). 

It also notifies the user when a new video is uploaded (at app startup).

Bookmarking videos is actually a good idea.  I'll add it into my TODO.

**Comment by ram-on** [comment]
Video bookmarking has been implemented.
