### ISSUE TITLE
How about ignore uploader feature?

### ISSUE THREAD

**Issue by HubKing** [ram-on/SkyTube#209]
When I search YouTube, there often are some video uploaders who either spams the search result with fake videos, or whose videos I simply dislike. I would like to exclude videos from them from search results, or from recommendations.

That feature is lacked in the official YouTube app, and that is why I am looking for an alternative client. It would be helpful if that feature is implemented.

**Comment by ram-on** [comment]
Hello @HubKing.  It is indeed a good idea and a must have feature.  It was being discussed at #193.  The feature is in the pipeline.
