### ISSUE TITLE
Can we have a feature which allows users to download videos offline?

### ISSUE THREAD

**Issue by Raj2032** [ram-on/SkyTube#211]
Is it possible for this app to allow users to download the videos offline and it can either be stored on the app itself or it can be downloaded as a mp4, avi etc?

**Comment by ram-on** [comment]
Hi @Raj2032, we've just implemented it -- refer to #208.  It will be available in the next release.

**Comment by Raj2032** [comment]
When is the next release coming out?

**Comment by ram-on** [comment]
Probably January 2018

**Comment by Raj2032** [comment]
Oh ok thanks and happy new year

**Comment by Raj2032** [comment]
Is it possible to also make a Windows, OS X and GNU/Linux version as well?
