### ISSUE TITLE
Basic Blocking feature implemented. Cant commit. 

### ISSUE THREAD

**Issue by okan35** [ram-on/SkyTube#217]
Hi ram-on I added basic blocking feature. On main page where you see videos, when you click to drop down menu, you see block channel. After clicking block channel, first you need to refresh then it does not get any more videos from that channel. But problem is I can't commit it to github. Github gives me problems. Is there any other way I can send you the code and files?

**Comment by atomjack** [comment]
@okan35 Can you elaborate on the exact problems with github? This is the proper procedure for sending updates for the app:

1) Fork the repository into your own account.
2) Create a branch in your forked repository for the feature you want to add.
3) Push the branch up, and create a Pull Request (PR), for @ram-on to review.

Did you follow these procedures? What exactly did you do?

One thing to keep in mind is that if there have been additions to the main repository (this one) since you created your branch, there could be conflicts with your branch, which will prevent your PR from being merged. If this happens, you have to either merge those changes into your branch, or rebase the master branch (from either this repository, or your fork's master branch after you've merged the changes into it) onto your branch. Using either of these methods will then show the conflicts, and you will have to edit the conflicting files so they work properly. If this is confusing, you'll need to read up about merging and rebasing.

**Comment by okan35** [comment]
Hi atomjack, I forked and downloaded this repository some time ago. The problems I got were about merging conflicts. I guess those changes in the main repository are giving me problems. I tried everything regarding error outputs from git on terminal. But nothing worked. I was able to push once but it was a force push to the fork I did. I will try to fork again and follow your steps. When I have errors that I can't fix, I will write them here.

**Comment by atomjack** [comment]
@okan35 First, you should add a remote for the upstream repository (this one) and fetch from it:

```
git remote add upstream git@github.com:ram-on/SkyTube.git
git fetch upstream
```

Then, switch over to the master branch on your fork, and update it with the master from upstream:

```
git checkout master
git rebase upstream/master
```

That will update the master branch of your fork with all the changes to the upstream master branch (upstream == this original repository). Then, you can switch back over to your branch and rebase master onto it, which will rewind all the changes you made on that branch, update the branch with the latest commits from master, and then re-apply the commits you had made on your branch (which will likely cause conflicts, which you will have to resolve):

```
git checkout <branch>
git rebase master
git status
```

It will likely show a bunch of stuff, and then say conflicts were found. The last line will show you which files had conflicts - you'll have to edit those files and find the parts where the conflicts are, and fix them (merge the code together so everything works properly). Once you are done editing the files, you should compile the app and install it on your device to make sure everything works properly. Once that is done, you'll have to add those files and continue the rebase:

```
git add <file that had conflicts>
(repeat for all files that had conflicts)
git rebase --continue
```

Once it's all done, you'll need to do a force push when pushing your branch up to your fork:
`git push -f origin` (read more on rebasing to see why this is). If you're in the middle of a rebase and want to abort it, just do `git rebase --abort`. One thing you may want to do is make a copy of your branch before you rebase it, as a backup: `git checkout -b branch-name-pre-rebase` (and then switch back to the original branch).

Good luck!

**Comment by okan35** [comment]
Hi atomjack, when I even do git fetch upstream I get permission denied error, even if I use "sudo". I checked about it on google and it is about ownership of repo. I need the read only link and also when I download directly from repo I get the error for some youtube api, I fixed this before by downloading folder and putting into necessary place but I guess doing this creates problems.

**Comment by atomjack** [comment]
@okan35 Did you try `git rebase upstream/master` ? The url I gave for adding the upstream repo has read access, you shouldn't have to do anything else.

**Comment by okan35** [comment]
@atomjack I tried but I get needed single revision error I also did what SO suggests it is not working. I actually done a contribution to another project before it just went smooth, I do not understand why is it hard now. Why do I get error I have no idea ?

**Comment by ram-on** [comment]
Hello @okan35.  Recently we did some major restructuring to the app's packages and hence that's why you're experiencing such errors.  I suggest that you re-clone my github and then copy and paste your changes.

**Comment by atomjack** [comment]
@okan35 If you made your changes on a separate branch (than master) on your fork, and have pushed/can push that branch up to github, you could try cloning your fork into a new directory, then add @ram-on's upstream, and try to rebase your branch from there. It's an option, anyways.

**Comment by okan35** [comment]
@ram-on @atomjack  I will reclone the repo and make changes on it. Hopefully this time it will work.

**Comment by okan35** [comment]
Before making the changes I just wanted to ask about these errors.
https://i.imgur.com/PAoYjjs.png

I get them from the newly cloned repo, Should I still make the changes ?  I think I fixed these error by literally copying files from your github or from the source I don't quiet remember.

**Comment by atomjack** [comment]
@okan35 Yeah, you need to run the following:

```
cd app/src/main/java/org/schabi/newpipe
git clone https://github.com/ram-on/extractor.git
```

If you run into more problems with git after that (rebasing etc), paste the output in a new comment here (see [Mastering Markdown](https://guides.github.com/features/mastering-markdown/), specifically under "code", for how to format it like the above git commands I did).

**Comment by okan35** [comment]
@atomjack @ram-on Hi, I finally did it, I made a pull request and hopefully it is fine so that this feature can be available.
