### ISSUE TITLE
Navigation bar visible while video is playing.

### ISSUE THREAD

**Issue by Aggornaut** [ram-on/SkyTube#219]
As stated in the title, the Android navigation bar is not hidden while a video is playing. 

This issue is only present while using the default player. It disappears as expected while using the Youtube player. 

Android version 7.0.

**Comment by ram-on** [comment]
@Aggornaut SkyTube version 2.80 has been released.  Can you confirm if this has been fixed?

**Comment by Aggornaut** [comment]
Seems to be working fine now. Thanks!
