### ISSUE TITLE
Can we have more Operating Systems support please

### ISSUE THREAD

**Issue by Raj2032** [ram-on/SkyTube#230]
Can we make SkyTube applications for Windows, OS X and GNU/Linux please, as well as a web version.

YouTube has become horrible to use. I don't really have fast Internet and everytime I let my videos buffer, after several hours later I would come and watch the video and guess, what, it gets deleted from the RAM. Since YouTube now deletes everything from the RAM if the video has not been watched for hours.

There are other issues with using YouTube for example,

- Serious privacy issues
- Can't download videos offline
- Geo restriction issues
- YouTube has removed a feature where users can reply to any YouTube video comments within the current page that they are in, Google decided to remove that feature.

I know that SkyTube is far better than YouTube and I was hoping if it can support more platforms. Thanks :)

**Comment by ram-on** [comment]
Unfortunately it is not feasible to port SkyTube to other operating systems as is very much dependent to Android.  This means that in order to port it to other operating systems, we have to rewrite the whole code, and hence it is not feasible.

What I suggest is that you use an Android emulator such as BlueStacks and run SkyTube on it.

**Comment by Raj2032** [comment]
How about just having a web version of SkyTube instead?

**Comment by ram-on** [comment]
@Raj2032 Again, a web version of SkyTube means a total rewrite.  Have you tried hooktube.com ?

**Comment by Raj2032** [comment]
Is HookTube
- Free (as in freedom) and Open Source?
- Does it give personalised video suggestions (just like in YouTube)?
- Can you sign in with your Google account to get your history and other
stuff?

**Comment by ram-on** [comment]
@Raj2032 Most probably the answer for all the above points is no.
