### ISSUE TITLE
NewPipe Extractor throwing errors: package org.junit does not exist

### ISSUE THREAD

**Issue by atomjack** [ram-on/SkyTube#239]
I wanted to try out the new swipe controls branch but ran into an error with the extractor module, so I updated (did a git pull) that, but it's throwing different errors now:

```
Error:(8, 24) error: package org.junit does not exist
Error:(8, 1) error: static import only from classes and interfaces
```

Wasn't able to figure anything out. Any ideas, @ram-on  ?

**Comment by ram-on** [comment]
Hello @atomjack, try to delete this folder:  `<SKYTUBE_PATH>/app/src/main/java/org`

**Comment by atomjack** [comment]
@ram-on  Oh interesting, SkyTube doesn't depend on the NewPipe Extractor anymore?

**Comment by ram-on** [comment]
No, just the extractor lib dependency is now part of the gradle file.

**Comment by atomjack** [comment]
Ah I see, awesome.
