### ISSUE TITLE
SkyTube should change to MIT license

### ISSUE THREAD

**Issue by Raj2032** [ram-on/SkyTube#244]
Reason why I suggest this is cause GNU licenses tend to be more restrictive, as the user who wants to fork SkyTube would be forced to make their distribution open source instead of doing whatever they want to do to it; having these sort of restrictions in place does reduce the freeness within the software.

**Comment by ram-on** [comment]
The reason why the GNU licence was chosen is because it is restrictive.  I don't what people using and improving the code for their own advantage without contributing back to this project.

**Comment by Raj2032** [comment]
But then how can people own the software if you restrict people's rights?

**Comment by herrwusel** [comment]
I don't get it @Raj2032 . A person dedicates his time to make an app for free as in beer and you complain that the license is bad because you can't own the code. I guess this code is not meant to be owned, is it?

**Comment by Raj2032** [comment]
According to an article https://vaporsoft.net/gpl-sucks/, making software
GPL licensed makes the software NOT truly FOSS. in order to make it truly
FOSS, it should stick with MIT license.

**Comment by ildar** [comment]
May I suggest @Raj2032 reading RMS @ gnu.org site why "owning the code" is
bad? And I don't call to discuss these matters HERE.

**Comment by Raj2032** [comment]
What I am trying to say that this software can't be fully truly free
software, that is what I am saying here. Plus this issue is already closed,
may I ask how come it is a bad idea to discuss it over here?

**Comment by herrwusel** [comment]
it depends on how you look at it. You say it isn't free because you can't do with it what you want. I say it is so free that people using this code need to make it open accessible.

**Comment by ram-on** [comment]
This app is free provided that everyone shares the source-code.  It's a fair deal in the sense that I'm sharing the source code (for which me and other devs developed in our spare time - free of charge) and third parties have every right to view, study and audit the source code and also modify and monetize it ... provided that such third party publishes any changes to the source code so that the whole community can gain from such changes.

**Comment by mhmdanas** [comment]
To be clear, you don't have to share the source code if you make any changes. For instance, if you made a modification to the code and you didn't send anyone a copy of SkyTube compiled with that modification, you are not obliged to publish the modified source code. For more information, read https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic.
