### ISSUE TITLE
Differences in non-OSS Extra version

### ISSUE THREAD

**Issue by MikeLund** [ram-on/SkyTube#245]
Hi, I just found this project and it works well, good job!

However, I was initially turned off by the vagueness of the "Open source app with extra features" description for the SkyTube Extra version. I looked around for more information in other issues, but I couldn't find it.

So I think it'd be useful if there was a little bit more information given on the difference of the fully-OSS version. Cheers!

**Comment by ram-on** [comment]
Hello @MikeLund.  The code of both flavors is open-source and protected by the GPL.

However SkyTube Extra also contain the default YouTube player which is basically a closed source library developed by Google.  In the near future, SkyTube Extra will also contain the Chromecast functionality - again such functionality is provided by a third party library which is also closed source.

Hence, SkyTube Extra is an open-source app that makes use of third party non-opensource libraries.

**Comment by MikeLund** [comment]
So basically the only real difference is from a few libraries extra used: currently the proprietary YT player, and eventually Chromecast functionality. Thus there's nothing missing from the libre version, if one doesn't want to use YT's player or the Chromecast. Thank you for the clarification!
