### ISSUE TITLE
Extractor error after fetching upstream

### ISSUE THREAD

**Issue by okan35** [ram-on/SkyTube#246]
@ram-on Hi Ramon I just got this error after I synced the forked repo with upstream. 

https://i.imgur.com/DNquSlL.png

I did not want to change anything before asking here, I assume it is about some package changes or I am not sure as if I make service list public that also creates new errors. Do you have any idea about this ?

**Comment by ram-on** [comment]
@okan35 Please delete the following directory:  `app/src/main/java/org`

**Comment by okan35** [comment]
thanks, that helped.
