### ISSUE TITLE
Alphabetical order for subscribed channels drawer

### ISSUE THREAD

**Issue by okan35** [ram-on/SkyTube#257]
I really would like to have my channels in a alphabetical order and also maybe a small search box in which I can type letters and it will start to show related subscribed channels. So I don't have go up and down to find a specific channel.

So these two features would be great. 
-Alphabetical order of subscribed channels in subscribed channels drawer. 
-A small search option in Subscribed channels drawer to find the specific channel fast.

These things are problem if you have lots of subscribed channels

**Comment by atomjack** [comment]
Agreed!

**Comment by ram-on** [comment]
Sounds great.  Add the alphabetical order in the preferences.

For the channel search thingy, I suggest that we add a search icon near the "Subscriptions" title and once it is clicked a search box will appear beneath it, like this:  https://i.imgur.com/SXR7wPz.jpg

**Comment by okan35** [comment]
That is what I was thinking exactly. This will make usage way easier. I am not sure if I can work on this now. If anyone can start, it would be great otherwise I will work on it later.

**Comment by okan35** [comment]
Hi @ram-on I am able to put the channels alphabetically, soon I will make a pull request after I make a new branch cleanly. After this is done I will work on search feature for subscribed channels.

**Comment by ram-on** [comment]
@okan35 Great.  Please make sure that you use tabs for indentation and not spaces.  Also, I recommend that you start working immediately on a branch rather than on your main.

**Comment by okan35** [comment]
You know what I actually don't use spaces. It is maybe my Android studio settings are using spaces because I don't really press space (I would hate it) a couple of times to indent code.

And yeah I will work on a different branch.

**Comment by ram-on** [comment]
@okan35 To fix the indentation problem, go to Android Studio > Preferences (or Settings) > then refer to the below screenshot:

![Android Studio Preferences](https://i.imgur.com/dtu7Chx.png)

**Comment by okan35** [comment]
Thanks, I did that.

**Comment by ram-on** [comment]
Feature implemented.
