### ISSUE TITLE
Playback starts over after visiting channel while viewing video

### ISSUE THREAD

**Issue by atomjack** [ram-on/SkyTube#26]
To reproduce:

- Start watching a video, and let the video play for awhile, so that the time readout displays something other than 00:00
- Tap the i icon in the bottom left to bring up video info, then tap on the channel icon to show the Channel Browser screen.
- Tap the back arrow or back button to return to the video, and notice the video starts playing from the beginning, instead of resuming from where it had been.

(I'd be happy to work on this)

**Comment by ram-on** [comment]
Thx @atomjack

**Comment by ram-on** [comment]
Done.  Refer to 22a31cc55caad64c9aa976679706fd9f2a535527.
