### ISSUE TITLE
Subscription DB is not initialized if the app is started without network

### ISSUE THREAD

**Issue by gzsombor** [ram-on/SkyTube#260]
Because SubscriptionsDb.getSubscribedChannels after asking the database, it asks the Youtube servers about more channel informations. This throws an exception, but that exception is catched, and an empty list is returned. In the end, the UI shows the warning about that there isn't any subscription yet - which is freaky a bit. The bigger problem is, that the user needs to force-stop the app, and restart it, after they connect to a network to get back their subscriptions / video list.
 I suggest to store all the channel informations locally for the subscribed channels, what do you think?

**Comment by ram-on** [comment]
Good catch.  We can either cache the subscribed channels' info or add the subbed channels inside a SwipeRefreshLayout.
