### ISSUE TITLE
Playback menu above the video

### ISSUE THREAD

**Issue by Pararena** [ram-on/SkyTube#261]
The playback menu appears above the video. i didnt see this on the changelog so it's probably a bug (if not than id like the option to revert it)

**Comment by ram-on** [comment]
Hi @Pararena.  What do you mean  by "playback menu"?  Can you submit a screenshot?

**Comment by Pararena** [comment]
![screenshot 2018-03-06 at 14 02 06](https://user-images.githubusercontent.com/37123190/37066522-4a440042-21bf-11e8-832f-3f8ebe708445.png)

**Comment by okan35** [comment]
That is the first time I ever see something like that.

**Comment by ram-on** [comment]
That's actually a bug -- This is now resolved as I've rewritten the player.  An updated version will be released soon, hopefully within 1 month.
