### ISSUE TITLE
New logo for SkyTube

### ISSUE THREAD

**Issue by reallinfo** [ram-on/SkyTube#266]
Hello, I designed a logo for SkyTube. If you like it, I will give you this logo as a gift.

![logotype](https://user-images.githubusercontent.com/36298335/37279458-8b7efc50-25f3-11e8-83a0-348caf7e5a68.jpg)

**Comment by ram-on** [comment]
Hello @reallinfo.  That's actually nice, a much needed upgrade.  Thanks!  Is it possible to share the source file?

**Comment by reallinfo** [comment]
Of course there is.. Here you are. I would be very happy if you use this
logo. :)


2018-03-13 23:15 GMT+02:00 Ramon <notifications@github.com>:

**Comment by ram-on** [comment]
@reallinfo The source file was not attached with the previous message.  Most probably it was automatically removed by GitHub.  It is possible to place it inside a Zip file and submit it via the GitHub website?

**Comment by reallinfo** [comment]
[skytubelogo.zip](https://github.com/ram-on/SkyTube/files/1808736/skytubelogo.zip)
Is it ok?

**Comment by reallinfo** [comment]
I sent.


2018-03-13 23:32 GMT+02:00 Ramon <notifications@github.com>:

**Comment by ram-on** [comment]
@reallinfo yeah I've received it.  Much appreciated!

**Comment by reallinfo** [comment]
Thanks!

**Comment by ram-on** [comment]
Hi @reallinfo.  Your icon is now being used as the launcher icon for the SkyTube app.  Many thanks for your contribution!

**Comment by reallinfo** [comment]
You are welcome, goodworks!
