### ISSUE TITLE
high resolution video download

### ISSUE THREAD

**Issue by Beapal** [ram-on/SkyTube#268]
Videos are download at 348p even after setting high resolution in player preference.

So, whats the way to download 1080p ?

**Comment by ram-on** [comment]
@Beapal Can you indicate the videos which are being downloaded as low res files?

**Comment by Beapal** [comment]
Thank you for the repond. 

Sky tube is downloading high resolution as set in video player preference.

It was VLC Android didnt refresh video resolutions even deleting and redownloading.

Sky tube rocks.
