### ISSUE TITLE
Download video as audio

### ISSUE THREAD

**Issue by ghost** [ram-on/SkyTube#269]
Option to choose whether to download as video or as audio.

**Comment by davidhedlund** [comment]
Yeah, like [NewPipe](https://f-droid.org/en/packages/org.schabi.newpipe/).

**Comment by davidhedlund** [comment]
By the way, how do I even download videos?

**Comment by ram-on** [comment]
@davidhedlund Refer to the below screenshots:

https://i.imgur.com/t8Oganv.jpg

https://i.imgur.com/AizE0wS.jpg

**Comment by davidhedlund** [comment]
Thanks but I cannot find the `Download` item on SkyTube Version 2.91 on https://f-droid.org/en/packages/free.rm.skytube.oss/ albet it's text says:

>  download videos,

**Comment by ram-on** [comment]
If you are using mobile network such as 4G, then you need to go to the preferences and tick "Allow downloads on mobile network":  https://i.imgur.com/AizE0wS.jpg

**Comment by davidhedlund** [comment]
Thanks, but why isn't this enabled by default? Most people will not know about this.

**Comment by ram-on** [comment]
> maybe it would be better to keep the menu entry and only disable it, or keep it enabled and show a warning message "you are on mobile and cant download, go to settings and enable it" or something?

Good point.  Will be implemented.

**Comment by davidhedlund** [comment]
> Will be implemented.

Should we open a separate issue for this?

**Comment by ram-on** [comment]
> Should we open a separate issue for this?

@davidhedlund Yes pls.  I would appreciate that!

**Comment by gzsombor** [comment]
Duplicate of #118
