### ISSUE TITLE
[Suggestion] Add option to export subscriptions

### ISSUE THREAD

**Issue by bastadur** [ram-on/SkyTube#27]
Yeah.

**Comment by xamica** [comment]
Any work in this area? I want implement it, if nobody else want do it. It will be great to see some roadmap with any timeline, where I can see priority of some tasks.

**Comment by ram-on** [comment]
@xamica Feel free to implement it - its in the pipeline anyway.  I would like it to be done via XML.

**Comment by ram-on** [comment]
Implemented subscriptions and bookmarks imports (d29960a8fbc1ac85d5ae04478f832073d58f656d) and exports (62edab8e962bbade66fe94a86c2d80e05b9c5de2) functionality.
