### ISSUE TITLE
New logo for SkyTube

### ISSUE THREAD

**Issue by Dnaart18** [ram-on/SkyTube#271]
Hi, I'm designing a logo for SkyTube. If you like it, I will give you this logo as a gift.
![icon](https://user-images.githubusercontent.com/37586134/37660517-303997fe-2c85-11e8-8ede-15c21422dc07.png)

**Comment by ram-on** [comment]
Thanks @Dnaart18 !  Now I have to choose between this one and that of #266.  Can you share the source file?

**Comment by Dnaart18** [comment]
here sir https://drive.google.com/drive/folders/1Pai6lDuozJALJ_Uw1HJ2K28CifMVENAz?usp=sharing

**Comment by ram-on** [comment]
@Dnaart18 I think you've shared the wrong folder

**Comment by Dnaart18** [comment]
no one seems. inside the folder has original logo file

**Comment by ram-on** [comment]
@Dnaart18 The shared folders only contain files relating to a casino logo.

**Comment by Dnaart18** [comment]
Omg!!!! ,, im sorry tomorrow I will reupload :)

**Comment by Dnaart18** [comment]
this is the correct link sir https://drive.google.com/drive/folders/1RvqudoHz2wxhTKrnFhHa_3-JlIyIq9GS?usp=sharing

**Comment by podanrj** [comment]
hi @ram-on what do you think? this is will be used for [the project](https://github.com/ram-on/SkyTube/issues/266 )?  or u will use this [one](https://drive.google.com/drive/folders/1Q-fzSovm2v2ZopQYnrHhqNvqnsAG74B3).?

I need your quick feedback.?

**Comment by ram-on** [comment]
Hi @Dnaart18, I had to choose between this icon and the one listed in #266.  Both icons are very professional and good looking.  Unfortunately I've chosen the #266.  Nevertheless, I would like to thank you for taking the time and effort in creating the icon!
