### ISSUE TITLE
Subscriptions deleted

### ISSUE THREAD

**Issue by stemy2** [ram-on/SkyTube#273]
Hello,

I subscribed to 54 channels, but for an unexplained reason, this number is now 0.

It happens regularly, but this time, even restarting my phone doesn't solve it.

**Comment by ram-on** [comment]
Hi @stemy2, can you please provide more insight on how to replicate this bug?

**Comment by stemy2** [comment]
Honestly, i really don't know what's the origin of the problem. It appears for an uknown reason at app launch and is resolved itself, except the last time.

Additionnally, i have another problem.

I searched some terms, no results. I pressed back, and i saw -not without surprise- all the videos of my subscriptions, with an empty list of subscriptions. At this step, if i refresh, all the videos disappears, and if i click on the youtuber's nam, the app crash.

I'm sorry, i can't give more informations.

**Comment by ram-on** [comment]
@stemy2 That could be because the app exceeded the YouTube API quota.  Try to enter your own YouTube API via Preferences > Others > YouTube API key.  That will fix any of these issues.

**Comment by stemy2** [comment]
Thanks for your answer. It made me think that i blocked the google apis with an app wich can block system wide requests (AdAway). So i unblocked it, then my skytube works again.

**Comment by okan35** [comment]
@ram-on  In my opinion it was because of internet connection, which gave null result to the lists which crashed the app.
