### ISSUE TITLE
[Feature Request] Desktop Version

### ISSUE THREAD

**Issue by D-Ermis** [ram-on/SkyTube#276]
Hi -- SkyTube is great and I use it daily on my Android phone. 
I'm looking for a youtube alternative for Windows.
Do you think it's feasible to port SkyTube to Desktop or as a web app? It'd be soo great!

Thanks and keep up the good work!

**Comment by ram-on** [comment]
Hi @D-Ermis, the source code of this app is very tightly knit with Android as it only uses the Android API making it very difficult to port it to Windows.  The only way to run it on Windows is by using a virtual machine or emulator such as BlueStacks or run Android-x86 inside VirtualBox.

**Comment by DI555** [comment]
I wanted to post the same issue also). And tryed to find some desktop app and didn't find it so comfortable like SkyTube!(and some other one android app;) But would be great to be desktop version! Is it built now of java, yes?
Is possiple place this feature in todo list, please?
Many thanks in advance!

**Comment by PoorPocketsMcNewHold** [comment]
You guys might prefer using [FreeTube](https://github.com/FreeTubeApp/FreeTube/tree/a89a651cd67072226236012d540966f64455345e) for a desktop application based on the same principals instead on relaying on an android emulator.
As for a web app, You should really take a closer look to [Invidious](https://github.com/omarroth/invidious/tree/52cb2391949cb06763bab1d52b93ca2210860683).
