### ISSUE TITLE
Channels are not sorted after the app is re-opened

### ISSUE THREAD

**Issue by ram-on** [ram-on/SkyTube#280]
Channels are not sorted after the app is re-opened.  Bug can be reproduced as follows:

1. Subscribe to a number of channels
1. Go to Preferences > Others > Sort by channel
1. Close/Kill the app (https://i.imgur.com/wrCRSHC.jpg).
1. Re-open the app.  Once re-opened, the channels are not sorted alphabetically.

**Comment by ram-on** [comment]
@okan35

**Comment by okan35** [comment]
@ram-on I will check it again, it is possible that I forgot to commit some code.

**Comment by okan35** [comment]
@ram-on  I checked it and I literally don't understand how this is not working as shared preference is working from my understanding. Because from the outputs of Loggers that is what I see. Everything is true even inside the if else in `getSubList` but still it does not sort the channels after restarting the app. 
you can find the code here https://gist.github.com/okan35/5d2cc9ba6143580fe73edb3b9428528d

**Comment by ram-on** [comment]
@okan35 The code in your branch is different than the one is the master.  More specifically:

```java
// code in your branch
public void setChannelsSorted(boolean channelsSorted) {
	Logger.i(TAG, "setChannelsSorted: channelSorted "  + channelsSorted);
	this.isChannelsSorted = channelsSorted;
	editor.clear();
	editor.putBoolean("isChannelSorted", isChannelsSorted);
	editor.commit();
	Logger.i(TAG, "setChannelsSorted: isChannelSorted " + isChannelsSorted);
}
```


```java
// code in master
public void setChannelsSorted(boolean channelsSorted) {
	isChannelsSorted = channelsSorted;
	editor.putBoolean("isChannelSorted",isChannelsSorted).apply();
}
```

There is for sure bug at the first line of the master's `setChannelsSorted()`:  isChannelsSorted is being copied to its self...

On a side note, do NOT manually copy code from your master to the branch.  Always work on a custom branch and then, before you commit a Pull Request, make sure that your branch is up-to-date and reflecting the master.  Follow this guide:  https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by okan35** [comment]
I will do the rebasing or creating a clean branch but just wanted to fix it firstly. The one that I just showed you in that file is also not working, I made those changes now otherwise it was the same as master.

**Comment by okan35** [comment]
@ram-on I fixed the issue, at least it seems like that. Everything was correct actually but I just was not updating the UI, now I do it and it seems ok to me.

**Comment by ram-on** [comment]
@okan35 This issue appears to be resolved, somehow...  Closing this issue.
