### ISSUE TITLE
Regression found on channel blocking feature

### ISSUE THREAD

**Issue by atomjack** [ram-on/SkyTube#281]
I recently noticed that after unsubscribing from a channel, the videos from that channel still appear in my Feed tab. I did some research and found that this is due to a change that @okan35 did with the channel blocking feature. Specifically, when the unsubscribe method of SubscriptionsDb is called, it is no longer deleting videos from the channel that is being unsubscribed from.

https://github.com/ram-on/SkyTube/commit/8196c0e0385ea0298ea8dec06c7b179d20419d15#diff-fbec8a0b2d35215970991ca44f26c808

@okan35, can you explain why you removed those lines from the unsubscribe method? Can I go ahead and make a PR that puts them back? cc: @ram-on

**Comment by okan35** [comment]
@atomjack I thought those lines were doing the same thing basically and asked also @ram-on about it if I should delete them and he said yes so I deleted.

**Comment by ram-on** [comment]
@atomjack @okan35 My bad, I misread the SubscriptionsVideosTable as SubscriptionsTable.  I'll add them back

**Comment by ram-on** [comment]
Fixed as per 42c142c2c0eeefe6d1ecb158a7aa1451d04ddd5c

**Comment by atomjack** [comment]
Cool thanks!
