### ISSUE TITLE
Problem with Subscription Importation from YouTube

### ISSUE THREAD

**Issue by Thorsky24** [ram-on/SkyTube#283]
Hello,

I just wanted to ask if it would be possible to allow .bin files in order to import YouTube subscriptions. I didn't manage to import an XML file: maybe it was the former format but it has been changed.
Otherwise, if it is still possible to export an XML file from YouTube, is it possible to tell me how?

Thanks in advance and for the development of the app :)

**Comment by atomjack** [comment]
@Thorsky24 I'm not sure where you can get .bin files that have YouTube subscriptions, but can you elaborate on the problems you're having importing the xml file? One thing I noticed is that Chrome for Android doesn't give the downloaded xml file an xml extension, so you'll have to rename it with a file manager before you attempt to import it (the in-app file browser doesn't see it if it doesn't have a .xml extension).

**Comment by Thorsky24** [comment]
You were right, it was a problem linked with my browser. We can close this issue. Thank you for the help :)
