### ISSUE TITLE
mobile data is used even if downloads on mobile networks are disabled

### ISSUE THREAD

**Issue by GoTeamAnt** [ram-on/SkyTube#285]
Hello

I have a Google Pixel with Android 8.1 (currently) and SkyTube uses my 1GB mobile data package even tough I disabled downloads on mobile network

My settings are:

SkyTube:

- Allow downloads on mobile networks [disabled]

relevant Android:

- WiFi [enabled]
- Mobile data [enabled]
- Agressive Wi-Fi to mobile handover [disabled]
- Mobile data always active [disabled]

I am watching videos only on wifi when I am at home, but somehow mobile data is used by SkyTube

Expectation:
Stop playing videos if wifi is not available.

**Comment by GoTeamAnt** [comment]
Thanks for the clarification.

I guess this is a feature request then.

Requested Feature:
Option to allow streaming of videos only on wifi (not metered connection).

**Comment by ildar** [comment]
Android has some means for that. Did you try?

**Comment by GoTeamAnt** [comment]
Care to share your knowledge with us Ildar?

How would I do this (besides disabling mobile data)?

**Comment by ildar** [comment]
Ahem,
https://duckduckgo.com/?q=android+restrict+mobile+data&iax=images&ia=images

**Comment by GoTeamAnt** [comment]
This images/links are about restricting background data, but Skytube uses foreground data.

Or did you have something else in mind?

I hate to be spoon feeded myself, but can you be very specific in your next post. Thanks in advance.

**Comment by ildar** [comment]
Ahh, you're absolutely right! I simply missed this point it's just about
background traffic.
Then the only good solution I know is AFWall / iptables. Sorry, man

**Comment by ram-on** [comment]
We've added a feature such that users are now warned before downloading/streaming videos on mobile network (such as 4G). This warning can be disabled. Refer to c171ee1.  I'm closing this issue -- feel free to reopen it if your issue is still persistent.
