### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [ram-on/SkyTube#287]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. This issue is not saying that your current logo is unsatisfactory, I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by ram-on** [comment]
As a matter of fact we've just changed the logo.  However, feel free to propose a new design for the logo.  Thanks!

**Comment by jbeguna04** [comment]
Thank you

**Comment by ram-on** [comment]
I'm going to close this issue - however, if you have any updated designs, please do not hesitate to re-open this ticket!
