### ISSUE TITLE
Change video resolution

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [ram-on/SkyTube#288]
It would be better if i can change  the resolution from 3 dots menu rather than going to the settings each time.
I like to watch some action videos in 720p and normal in 360p.

Also, please add a pop-up window like new pipe it will be convenient to watch videos.

Why did every video start in full screen mode can i watch it in the player like real youtube app and read descriptions and comments before playing the video?

Where is the subtitle option?

**Comment by ram-on** [comment]
Hello @Ashutosh-Kukreti.  I agree regarding the first two suggestions (resolution/quality:  #284; popup: #45).

Regarding the full screen mode, comments and descriptions can be viewed while playing the video by swiping to the left and to the top.

**Comment by Ashutosh-Kukreti** [comment]
I know it can be view using swipe but it'll be better if i can view like in official app before playing video.

[``](https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fi0.wp.com%2Fsocialbarrel.com%2Fwp-content%2Fuploads%2F2017%2F04%2FYouTube-Comment-4.png%3Fresize%3D666%252C588&f=1)


Also sometimes when the video pauses or interrupted it start playing from the beginning.

**Comment by ram-on** [comment]
> I know it can be view using swipe but it'll be better if i can view like in official app before playing video.

Hi @Ashutosh-Kukreti, I don't see any intrinsic advantage regarding that design -- will not implement.  Regarding the first 2 suggestions:  those will be implemented eventually.

**Comment by atomjack** [comment]
@ram-on For what it's worth, I too would like the ability to pull up a video's description before actually playing it. I'd be willing to work on that - maybe as another option in the Video options menu? To show a popup with the description?

**Comment by ram-on** [comment]
Hi Chris, the problem is that the options menu is really getting cluttered with data.  If we somehow manage to change some options (text) into just icons something like this:  https://i.imgur.com/xhXnKAE.jpg
		
Do you thinks its possible?
