### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [ram-on/SkyTube#292]
Sorry for making you wait for a long time, Let me propose again my designs in your project. Hope you like it!
![image](https://user-images.githubusercontent.com/35353768/39436056-87453a98-4ccf-11e8-9b68-2ff555f3ba9e.png)

**Comment by ram-on** [comment]
@jbeguna04 Thank you for your contribution.  Unfortunately we will be using icon designed by @reallinfo  (#266).  Nevertheless, I would like to thank you for taking the time and effort in creating the icon!
