### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by Hamzeto938** [ram-on/SkyTube#294]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by ram-on** [comment]
Hello @Hamzeto938, I don't understand what it meant by copywriting.  However, if you want, you can contribute by translating the app into your native language:  https://hosted.weblate.org/engage/skytube/

**Comment by ram-on** [comment]
@Hamzeto938 I'm closing this issue -- looking forward for your contributions.
