### ISSUE TITLE
Request to copy right. 

### ISSUE THREAD

**Issue by lilpellaola** [ram-on/SkyTube#295]
Hello there! I see you've a awesome project and I'm a big fan of skyTube and I'd like to request for you to grant me an opportunity to be part of this awesome project although I'm not a developer but I could add to it by helping with the copyright like writing Frequently Asked Questions(FAQ).. Looking forward to hear from you....

**Comment by ram-on** [comment]
I would really like it if you take part in translating this app in your native language.  Refer to https://github.com/ram-on/SkyTube/wiki/Contribute
