### ISSUE TITLE
playlist ID change

### ISSUE THREAD

**Issue by shaanvipul** [ram-on/SkyTube#296]
Hi i am new with android love ur code its really good i need ur help to modify playlist id in first tab so where is the option to change i try a lot but not got success please help me.

**Comment by shaanvipul** [comment]
Thanks sir i have read this first also and i am able to change name and all
but in this a need to play my playlist not youtube default page where i can
change playlist in featured Tab.
thanks for reply.

**Comment by ram-on** [comment]
Currently it is not implemented.
