### ISSUE TITLE
Logo design for skytube

### ISSUE THREAD

**Issue by harunbadilli** [ram-on/SkyTube#297]
I designed a logo for Skytube. With a logo similar to a YouTube app, I've made the Skytube app more distinctive and stylish. Skytube has now become more attractive.I can send it to you in any size and format. I hope you like it.
![1](https://user-images.githubusercontent.com/34319922/39960852-dba32250-5632-11e8-9dea-15595f2aca6c.png)
![2](https://user-images.githubusercontent.com/34319922/39960853-dbcc5986-5632-11e8-9863-c2a39fcc7ea1.png)
![3](https://user-images.githubusercontent.com/34319922/39960854-dbf60fba-5632-11e8-872a-95bcbbc6cb38.png)

**Comment by ram-on** [comment]
@harunbadilli  Thank you for your contribution. Unfortunately we will be using icon designed by @reallinfo (#266). Nevertheless, I would like to thank you for taking the time and effort in creating the icon!
