### ISSUE TITLE
When playing, sound suddently muted, then video stops

### ISSUE THREAD

**Issue by stemy2** [ram-on/SkyTube#300]
Hello,

I can't play entirely any video. Approximatively at the middle, the sound is muted for a couple of seconds, then playing is interrupted, even if the video is sufficiently buffered.

**Comment by ram-on** [comment]
Hello @stemy2.  This issue should be resolved as we're now using a new video player.  Can you please install the below APK and give it a try?  Once the app is running, go to Preference > Video Player > Set "Video Player" to "Default Player" and then play a video.

[SkyTube-extra-2.83.apk.zip](https://github.com/ram-on/SkyTube/files/2019517/SkyTube-extra-2.83.apk.zip)

**Comment by ram-on** [comment]
@stemy2 So, how did it go?

**Comment by stemy2** [comment]
Apparently, it seems to work fine.

**Comment by stemy2** [comment]
Actually, the bug i've submitted here is fixed in this version, but there are some other errors:
-The video description doesn't disappear anymore with a swipe down, so when i show it, i'm forced to watche the rest of the video with the description on it.
-The links in the description are not clickable and are just highlighted when i click on it.

**Comment by ram-on** [comment]
@stemy2 Thanks for your testing.  The links issue is now resolved.  As for the video description, that can be closed by clicking outside the video description.
