### ISSUE TITLE
Project Design

### ISSUE THREAD

**Issue by debpedrano** [ram-on/SkyTube#308]
Good day to you ! I am a designer, and I think your project needs logo and banner for ReadMe, if you need some. You can reach me via, not a problem on that .

**Comment by ram-on** [comment]
Hello @debpedrano.  Thank you for your interest in this project.  We already have an icon which was very recently designed.  As for a banner, yes feel free to design one.  Pls keep its theme in line with icon's theme.  Thanks!

**Comment by debpedrano** [comment]
@ram-on  hello, sorry for a late response. our internet provider was down, can I see the icon so that I can make a banner with the same theme. Thanks !

**Comment by ram-on** [comment]
Please find attached the current icon's theme:  [skytubelogo.zip](https://github.com/ram-on/SkyTube/files/2163922/skytubelogo.zip)

**Comment by debpedrano** [comment]
do you have any suggestions about this one ?

![image](https://user-images.githubusercontent.com/40510200/42416189-56382fea-829a-11e8-8d29-9b96db5b5174.png)

**Comment by ram-on** [comment]
Hi @debpedrano, thank you for your work.  I was more thing about a cleaner banner.  Maybe some bluish background with the logo in the middle.  Furhtermoer, I recon that it would be better if you remove the icon's box-border.

**Comment by debpedrano** [comment]
so you mean, the simpler the better @ram-on ? I will work on it :)

**Comment by realdmitchell** [comment]
May be you @debpedrano want to look into https://material.io/design/iconography/product-icons.html#design-principles
https://developer.android.com/guide/practices/ui_guidelines/icon_design
@ram-on Seems you have replaced the old icon with this blue in the master. The logo/banner is too complex. Better to have simple layouts. Then it looks better as icon. I know it is open source work. Just my suggestions. Hope not annoying you both.

**Comment by ram-on** [comment]
@debpedrano I'm closing this ticket due to inactivity.  Feel free to reopen it if you have any further feedback.
