### ISSUE TITLE
Background play

### ISSUE THREAD

**Issue by theman480** [ram-on/SkyTube#311]
Hello I really love your app, it's amazing, I am just missing one feature, the background playing, like the one with YouTube Venced, can you add it? Thank you in advance.

**Comment by Davy49** [comment]
Hi,
I agree with theman480 , I thought I read somewhere before I installed the app that it allowed at least music videos to be played in the background without stopping when the display was off. Without that feature it's really not any better than the regular YouTube application.
Thanks,
David

**Comment by ram-on** [comment]
Background play is partially supported now:  if the app is minimized while a video is playing, the video will now continue playing.

**Comment by ram-on** [comment]
Closing this issue as it is duplicate to #143
