### ISSUE TITLE
Youtube api keys' issue

### ISSUE THREAD

**Issue by LuqmanArif2051** [ram-on/SkyTube#319]
please can you describe why are you using 3 different youtube api keys and how and where can I get or create them. I'm new here thanks

**Comment by ram-on** [comment]
Use your Google account to login to https://console.developers.google.com.  There you can create a key for YouTube Data API v3.  There is no need to create 3 keys; 1 should suffice.

**Comment by LuqmanArif2051** [comment]
I have implemented your app and almost changed every thing but when I
upload on play store they reject every time with this reason "
*ssue: Violation of Device and Network Abuse policy " *
*can you solve my problem*

**Comment by atomjack** [comment]
@LuqmanArif2051 yeah that's because the app violates their policy, since it duplicates the official youtube app's functionality (which is run by google). You shouldn't be adding an app you didn't write to the play store, anyways.

**Comment by LuqmanArif2051** [comment]
what should I do now I want to upload on play store?

**Comment by atomjack** [comment]
@LuqmanArif2051 Write your own app? What the hell?
