### ISSUE TITLE
Navigation bar not hiding

### ISSUE THREAD

**Issue by Michkost** [ram-on/SkyTube#32]
While playing a video the navigation bar isn't hiding. Is this intended?

**Comment by ram-on** [comment]
Navigation bar should be hidden (automatically) when a video is playing.  You can (explicitly) tap in the middle to hide the nav bar.

**Comment by sthebemita** [comment]
Same here on android 5.1.1. The app's navigation bar does hide automatically and tapping, but the android one doesn't (in other youtube apps it hides automatically when you are in fullscreen mode). Also, it doesn't play in the background, but maybe this isn't a feature. Anyways, just wanted to say this is the best youtube app I've found!

**Comment by cmv47** [comment]
same issue ,android 5.1, please fix

**Comment by ram-on** [comment]
Fixed.
