### ISSUE TITLE
[ Feature Request ] - Text Size's Adjustment

### ISSUE THREAD

**Issue by aaaaaaaagrrla** [ram-on/SkyTube#328]
Can there be a setting that allow the Text size of interface / content  to be adjusted  (large range of adjustment). Also for individual elements such as the Text for the Video Length in the preview thumbnails.

**Comment by aaaaaaaagrrla** [comment]
There are not error. So no screenshot to submit. I experience problems as I use the app on a Standard Definition CRT television of 640x480 resolution.  These CRT tube televisions are blurry. So small text is impossible to see, Hence I asked for this adjustment.   Also small screens AND/OR low resolution screens will have this issue. its a issue of perception from the eyes to the screen, not to the interface (so no screenshot. You can imagine the problem on the devices I explained. For example video thumbnail previews Video Length digits would be tiny too small to see.).

**Comment by ram-on** [comment]
I'm using Android's default font size.  Android should take care in scaling the font according to the device and not the app.
