### ISSUE TITLE
[ Feature Request ] - Video Player Buttons Size

### ISSUE THREAD

**Issue by aaaaaaaagrrla** [ram-on/SkyTube#333]
The video player's buttons are smallish. Can there be a size option for these (that allow choosing between a wide range of sizes).

**Comment by aaaaaaaagrrla** [comment]
Do I need to ?.  I did not mean there was a bug on the size. I just meant They are small, why not have larger ones, easier to tap (on smaller screen and/or larger fingers). Maybe a size option. OK ?.

**Comment by ram-on** [comment]
I'm using the default button sizes provided by the ExoPlayer.  Won't Fix.
