### ISSUE TITLE
[ Feature Request ] - Search Results, Same As YouTube Official App

### ISSUE THREAD

**Issue by aaaaaaaagrrla** [ram-on/SkyTube#334]
If you compare the results (all of them) of a search, with the results of the official youtube app, they are different. Maybe some missing, some extra, some in different order, etc..

Can it be exactly the same as the Official Youtube app.

**Comment by ram-on** [comment]
The app is just getting the results from the Google servers and displayed as they are presented.  We don't have control on how such info is sorted.
