### ISSUE TITLE
[ Feature Request ] - Video Player, Buttons; Subscribe, Visit Channel

### ISSUE THREAD

**Issue by aaaaaaaagrrla** [ram-on/SkyTube#335]
Can there be buttons on the Video player (maybe on the right side edge of the screen, on the same section where the Play ,Back ,Forward buttons are) that allow Subscribing the channel, and Visiting the channel

**Comment by ram-on** [comment]
Swipe from the bottom to the top:  the video description area will be displayed and there you can subscribe to the channel.
