### ISSUE TITLE
Scaling while fullscreen/incorrect aspect ratio

### ISSUE THREAD

**Issue by L6Xv3kWu** [ram-on/SkyTube#340]
On a telephone with a 18:9 aspect ratio when in fullscreen the video is displayed not with vertical bars at the side as in the previous version but really fullscreen so with the wrong aspect ratio

**Comment by ram-on** [comment]
Can you give me a link to the video for which the above issue was noted?

**Comment by L6Xv3kWu** [comment]
Well any youtube video which is 16:9 is scaled to 18:9 on my mobile phone.
But if you really want a concrete example, try:
https://youtu.be/1uhE7PWfrYU

**Comment by d86leader** [comment]
By the way, 4:3 videos are also fit horizontally, cutting out a lot of top and bottom content.
Example screenshot: https://imgur.com/wWFznXH
Video in screenshot: https://youtu.be/_dlEm_2ke8k
I'm using skytube version 2.90, latest in f-droid

**Comment by ram-on** [comment]
Bug fixed.
