### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by Bebop182** [ram-on/SkyTube#342]
When you select "Downloads" as your default tab, the app will crash on all following launches.

Steps to reproduce:
1- install skytube via FDroid
2- launch skytube
3- go to preferences > others
4- select "Downloads" as default tab
5- kill the app
6- launch skytube again

Test device:
OnePlus One
Lineage OS 14
Android 7.1.2

**Comment by ram-on** [comment]
Bug resolved.  Thanks for reporting.
