### ISSUE TITLE
Can't play any video since yesterday

### ISSUE THREAD

**Issue by justcosmic** [ram-on/SkyTube#347]
When I try to play any video, I get the following error:

> **Video Playback Error**
> An error has occured while retrieving video's streams.

There is no issue with my connection because I can watch videos on Youtube in my browser. The same thing happened to the other popular Youtube app and the error I got there is more detailed - it seems to be related to how retrieved data is parsed, it can't match a certain regexp pattern. Is there a way to obtain more detailed error log in SkyTube? If not, I can provide an error log outputted by the other app if that might help.

**Comment by Norbert80** [comment]
The reasons are server-side at Google.

SkyTube can adopt this patch:
https://github.com/rg3/youtube-dl/commit/9a47fa35dd9dd2d53f4d3f088811ea29295991e5

NewPipe already already has a integrated a fix based on this patch.

**Comment by ram-on** [comment]
Issue has been resolved (refer to #345).  Either wait for FDroid to release SkyTube v2.91 or else just download SkyTube Extra v2.91 APK from GitHub:  https://github.com/ram-on/SkyTube/releases/download/v2.91/SkyTube-Extra-2.91.apk

**Comment by Norbert80** [comment]
See also:
https://github.com/rg3/youtube-dl/pull/17464
https://github.com/TeamNewPipe/NewPipe/issues/1659

**Comment by Norbert80** [comment]
Thanks for the quick fix!
