### ISSUE TITLE
[Error] Not playing Videos at all

### ISSUE THREAD

**Issue by rusty-genius** [ram-on/SkyTube#348]
Since today, whenever I want to play a Video, I get the error that the video stream can't be loaded. 
This errror occurs at any video I try to play.

I run the F-Droid version 2.90

**Comment by okkebal** [comment]
Same here. Same problem with Newpipe and Kodi

**Comment by ram-on** [comment]
SkyTube v2.91 was released yesterday in which such issue was fixed (refer to #345). Either wait for FDroid to release SkyTube v2.91 or else just download SkyTube Extra v2.91 APK from GitHub: https://github.com/ram-on/SkyTube/releases/download/v2.91/SkyTube-Extra-2.91.apk
