### ISSUE TITLE
Feature request - Share video button

### ISSUE THREAD

**Issue by neomodern** [ram-on/SkyTube#35]
Ideally similar to the YouTube app's one where 'Copy link' is available at the top, then it shows all the apps you can share with.

**Comment by Fatcakes** [comment]
Even just a copy link option would be fine.

**Comment by atomjack** [comment]
I've implemented this in #41. I think Ramon is pretty busy right now but hopefully he'll have time to merge it in along with my other PR's.

Here's a screenshot: http://i.imgur.com/BsrcteI.png

**Comment by ram-on** [comment]
Feature added to SkyTube.  Thanks @atomjack
