### ISSUE TITLE
Video brightness changing without user input

### ISSUE THREAD

**Issue by travala1** [ram-on/SkyTube#351]
I'm using SkyTube 2.91 (Integrated Video Player) with a Samsung Galaxy Tab S2 (2016) with official LineageOS 15.1 Build.

After introduction of the brightness swipe gesture in SkyTube 2.90 i noticed that each time a new video starts the video brightness increases permanently. After playing back 5-6 videos the brightness of the video ends up at 100%. This is without touching the new brightness swipe gesture. I tested this with only opening videos on the left side of the screen and using the hardware back button to get back to my feed,

This bug forces me to constantly manually change the video brightness setting after each video and is really annoying especially in low light conditions.

If this ends up being a device specific bug, can you please allow users to disable brightness adjustment by the app completely? With SkyTube 2.8 i had zero issues.

**Comment by ram-on** [comment]
Bug fixed, refer to 28d08d323d0c9501946629470120add8def3b397.
