### ISSUE TITLE
Swipe gesture settings

### ISSUE THREAD

**Issue by travala1** [ram-on/SkyTube#352]
Please introduce a settings section for the new swipe gestures in SkyTube 2.90 to enable or disable them.

It is really easy to trigger them accidentally. Especially with younger kids... they don't understand why suddenly the video is muted or very dark when they just wanted to point at something in the video or wipe off a speck of dust from the screen.

**Comment by ram-on** [comment]
Based on @Tvax's work, the video gesture can now be enabled/disabled from the preference.  This feature will be available during the next released.
