### ISSUE TITLE
[Feature Request] Enable/Disable video blocking feature

### ISSUE THREAD

**Issue by jEsuSdA** [ram-on/SkyTube#357]
Hi!

I recently update SkyTube and the new Blocking feature blocks thousands of videos.
There is no channel into blacklist and I can not find any way to disable the video blocking feature.

Is there any way to do that?
It could be possible to add any configuration settings to allow enable/disable this feature?

Thanks! ;)

**Comment by ram-on** [comment]
Hello @jEsuSdA It is possible that the videos are being blocked based on the language settings.  Tap on the video blocker icon to see why videos are being blocked (refer to the red boxes below):

https://i.imgur.com/o7PpipN.jpg

**Comment by ram-on** [comment]
I hope the above comment resolved your issue.  I'm closing this ticket.  Feel free to reopen if the above comment did not help you in resolving the issue.
