### ISSUE TITLE
Skytube crashes when playing a video with the default video player on Android 4.0.4

### ISSUE THREAD

**Issue by benages** [ram-on/SkyTube#360]
When I try to watch a video (with the default video player) on my old  Android 4.0 tv box the app just crashes. 
Using the legacy video player works.

**Comment by ram-on** [comment]
Hello @benages.  Unfortunately, Google is no longer providing virtual machine / emulator images for Android 4.0 (although I've tested out on Android 4.1 and it worked fine) and hence there is no way I can fix this issue.

**Comment by benages** [comment]
Hello.
I have found that Exoplayer only works on Android 4.1 and later: https://github.com/google/ExoPlayer/issues/86.
Thanks for making Skytube!!
