### ISSUE TITLE
Fire TV Errors

### ISSUE THREAD

**Issue by BlueFeather89** [ram-on/SkyTube#361]
Steps to reproduce:
1. Install and launch the app
2. Try to navigate and select app menu content using Remote and Gamepad

Actual Result: Observe video options does not get highlighted by way of visual cue
Expected Result: Interactive portions of the UI (like Play, Options, Settings) must appear highlighted usually by a rectangular box or other visual cue when selected by controller inputs so users don't have to guess which menu UI element is selected.

**Comment by ram-on** [comment]
Hi @BlueFeather89, Android TV's remote control will be support in future release.  Refer to #20
