### ISSUE TITLE
Enable "Allow downloads on mobile network" by default

### ISSUE THREAD

**Issue by davidhedlund** [ram-on/SkyTube#364]
> If you are using mobile network such as 4G, then you need to go to the preferences and tick "Allow downloads on mobile network": https://i.imgur.com/AizE0wS.jpg

"maybe it would be better to keep the menu entry and only disable it, or keep it enabled and show a warning message "you are on mobile and cant download, go to settings and enable it" or something?" - [obama](https://github.com/ram-on/SkyTube/issues/269#issuecomment-424819929)

**Comment by ram-on** [comment]
Hi @davidhedlund.  Issue should be resolved as now users are now warned before downloading/streaming videos on mobile network (such as 4G).  This warning can be disabled.  Refer to c171ee1c9b50228e525841dc18dbbc3bd1530e3b.
