### ISSUE TITLE
Unable to download videos 2.91 Extra

### ISSUE THREAD

**Issue by XiuOtr** [ram-on/SkyTube#366]
Videos do not download. Downloading <video name> toast message received followed by unable to download toast message several minutes later.  Storage permissions on.

**Comment by ram-on** [comment]
I'm unable to repliacte this error.  Can you attach the log file (generated from `adb logcat`)?

**Comment by XiuOtr** [comment]
I don't have root on this device to run logcat (S7 edge running Android 8.0). Is there another way to get it? Anything in dev options? Thanks.

**Comment by ram-on** [comment]
@XiuOtr If you are using Linux/macOS/BSD:

1.  Kill SkyTube
1.  Open SkyTube and try to download a video
1. Type the following command on your machine:
```bash
adb logcat -d --pid=$(adb shell ps | grep "free.rm.skytube.extra" | awk '{print $2}') > skytube.log
```

**Comment by XiuOtr** [comment]
On the same page now, but go ahead and close this.  Corruption was the issue. 

Out of curiosity I installed the OSS version and it downloaded videos fine.  Uninstalled it and reinstalled Skytube Extra. Downloads are working now.

If memory serves me right, a few weeks ago I may have accidentally installed Extra over top the OSS version without uninstalling OSS first.  That's probably when it broke. 

My apologies for the inconvenience. 
Thank you for the prompt responses.
And most of all thanks for developing Skytube. It's an awesome app!

**Comment by ram-on** [comment]
@XiuOtr Thank you for your kind comments.

**Comment by Flashwalker** [comment]
Oh, i see now, in my case it's a Movies folder.
