### ISSUE TITLE
App fails to launch when Downloads tab is set as default

### ISSUE THREAD

**Issue by TuriSc** [ram-on/SkyTube#368]
Steps to Reproduce:
1. 	Install and launch the app.
2. 	Navigate to "Preferences" > "Others" > "Default Tab"
3. 	Select "Downloads"
4. 	Leave the app and end its background process
5. 	Launch the app again.

Actual Result: The app fails to launch.
Expected Result: The app should launch and show the download tab.

The app can still be launched if invoked as a handler for a YouTube link.
	
Tested on Android 7.1.2 and 8.0.0.

**Comment by ram-on** [comment]
Thanks for reporting.  Issue resolved as per 3bcc6e1b5e8fb30a3a131f8717e3b9886ec8d794 which will be available in the next release.

**Comment by FichteFoll** [comment]
Oh, this might also be why it's been crashing on me for at least a week. Looking forward to a new release.
