### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by princekelly1** [ram-on/SkyTube#376]
Hello, I'm Kelly. 
I think having a privacy policy statement will be a good thing for your project seeing it kind of have functionalities that may lead to data collection on your end or not. It's a good end users are made aware of the safety of their privacy. I could draft a privacy policy statement if you wish. It's my way of contributing to open source projects.
If I may?

**Comment by ram-on** [comment]
Hello @princekelly1, thanks for reaching out.  SkyTube only saves bookmarks, subscriptions, downloads, blacklisted/whitelisted channel, video and search history.  Video and search history can be disabled by the user.  Feel free to draft a privacy policy accordingly.

**Comment by princekelly1** [comment]
Thank you, I will also draft a FAQ section to help users.

**Comment by princekelly1** [comment]
Am on it, thank you. Might add a FAQ document along.

**Comment by ram-on** [comment]
> Skytube saves user's Youtube API Key on the app??. If users decide to use their Youtube API?
 Indeed

The Privacy Policy Pull Request (#382) looks great!  I've merged it.  Thanks

**Comment by princekelly1** [comment]
Thats good., glad you like it.Thank you
