### ISSUE TITLE
[Feature Request] Option for disable/enable block filter feature

### ISSUE THREAD

**Issue by jEsuSdA** [ram-on/SkyTube#377]
Hi!
I have a lot of problems with the new block filter feature. It simply blocks a lot of videos and channels with no clear criteria.

So, please, could you add a configuration field to enable/disable the block filter.

Thanks a lot.

**Comment by ram-on** [comment]
@jEsuSdA Can you pls indicate examples of which videos were blocked together with the reason why they were blocked?  Can you perhaps provide screenshots of the video blocker?

**Comment by jEsuSdA** [comment]
Hi @ram-on . 
Here some blocked videos:

All videos blocked in this channel:
https://www.youtube.com/channel/UC_OLtzRJdg0MJfiqGWAAIHw

All videos blocked in this channel:
https://www.youtube.com/channel/UCkt41aFjWH9CwZAc0l1LZwg

All the non "es" videos blocked:
https://www.youtube.com/user/TEDxTalks

In "Destacados", all videos with lang "es-419" and other languages are blocked.


Does this help?

Thanks a lot!

**Comment by ram-on** [comment]
Thanks @jEsuSdA.

Regarding the "IDEAS EN 5 MINUTOS" channel:  you need to enable the "Español (Latinoamérica)" language via the Video Blocker > Preferred Language(s).

As for "APM? TV3":  the videos in that channel are marked as "Ca" (i.e. "Català" / "Catalan").  So you need to go to the Video Blocker > Preferred Language(s) and enable the "Català" option.

**Comment by ram-on** [comment]
Furthermore, just added an option to enable/disable the video blocker: c4f88701988bdbf5a8c9252715ff3af8d51dc068
