### ISSUE TITLE
Behaviour after disabled gesture control

### ISSUE THREAD

**Issue by kowith337** [ram-on/SkyTube#378]
### Expected behaviour
Screen brightness level while watching video should rely to system settings.

### Actual behaviour
Screen brightness level while watching video still rely to app settings that you've already set.

**Comment by ram-on** [comment]
@kowith337  I'll add a feature to always use system brightness.

**Comment by ram-on** [comment]
@kowith337 Resolved as per 7b04669a204ec1101a7cdbb26a6eb60a54a59454.
