### ISSUE TITLE
No Persian language in UI

### ISSUE THREAD

**Issue by ahangarha** [ram-on/SkyTube#380]
Hi

As you already know, Persian translation of the app is done just few days ago and it was also reflected in the recent changelog. Despite this, the app doesnt follow default system language when it is set into Persian.

I tried Spanish and it worked as expeceted, but Persian doesn't work. I only see RTL rearrangement of elements.

I tried to find a way to solve the issue, but couldn't find any clue from where to start.

**Comment by ram-on** [comment]
Hi @ahangarha.  It looks like that there are [3 different](https://github.com/championswimmer/android-locales) type of Persian locales:
1.  Persian = values-fa
2. Persian (Afghanistan) = values-fa-rAF
3. Persian (Iran) = values-fa-rIR

I'm assuming the Afghanistan's Persian is different than Iran's.  Maybe you can try to rename the "values-fa" folder to "values-fa-rIR" and confirm whether that works?

**Comment by ahangarha** [comment]
I didn't know from where to start. I will try with this clue

**Comment by ahangarha** [comment]
I just compiled the app with no changes made. It worked nicely with no problem in showing Persian translation, even on my phone (not just on VM)
But the official version still doesn't work with Persian.

**Comment by ram-on** [comment]
@ahangarha That's because such updates will be included within the next release.  Glad that it worked!

**Comment by ahangarha** [comment]
Just to make it clear, I made no change in the code except changing gradle version into 3.2.1 to be able to build.

**Comment by ahangarha** [comment]
@ram-on I have noticed both version (oss one, installed from fdroid and extra, compiled by myself) are save version: 2.92. Are you sure it will be solved by next release?
