### ISSUE TITLE
Contribution guide needs update

### ISSUE THREAD

**Issue by ahangarha** [ram-on/SkyTube#381]
Hi

I think the [contribution guide](https://github.com/ram-on/SkyTube/wiki/Contribute#developers-guidelines) needs to be updated:

1. Translation state needs to be updated
1. A simple guide on how to build the project needs to be included in this file (or somewhere else and linked in this guide)

**Comment by ram-on** [comment]
Hello @ahangarha,

1. The translation status diagram is provided by Weblate, we don't have control over it :)
2. To build  the app you need to download Android Studio, download SkyTube source code, open Android Studio, click on File > Open, select the directory holding SkyTube's code and then press on the green "play" button.

**Comment by ahangarha** [comment]
I could finally compile the app. I had problem with Gradle 3.2.0. I could compile with version 3.2.1

**Comment by ram-on** [comment]
Glad that it worked!
