### ISSUE TITLE
Offer plain Skytube download on GitHub

### ISSUE THREAD

**Issue by jidanni** [ram-on/SkyTube#384]
Offer plain Skytube download on GitHub too. All we can find is the extra version. We do not want to use F Droid.

**Comment by ram-on** [comment]
SkyTube (Vanilla) APKs will not be provided as they would have a different cryptographic fingerprint than those of FDroid.  You can download SkyTube apk directly from FDroids website (i.e. no need to install FDroid app on your device):  https://f-droid.org/packages/free.rm.skytube.oss/

**Comment by jidanni** [comment]
OK but e.g.,
- https://github.com/indywidualny/FaceSlim
- https://github.com/fetlife/android

also offer GitHub downloads too. Plus not a good idea to place all your eggs in one basket.
