### ISSUE TITLE
Subscribed channels not showing all videos

### ISSUE THREAD

**Issue by ejstacey** [ram-on/SkyTube#398]
I've noticed on a couple channels that some videos don't appear in Skytube, even though they appear in the RSS feed (what I assume Skytube uses).

Skytube 2.93 Extra on Lineage / Android 8

Some examples:

Primitive Technology ( https://www.youtube.com/feeds/videos.xml?channel_id=UCAL3JXZSzSm8AlZyD3nQdBA ).  The latest video "Primitive Technology: Pit and chimney furnace" does not show.

Perifractic's Retro Recipes ( https://www.youtube.com/feeds/videos.xml?channel_id=UC6gARF3ICgaLfs3o2znuqXA ).  The videos "Part 2: LEGO C64 Case Build #TheBrixtyFour - Own It, Win It!" and "Part 3: LEGO C64 With Sprung LEGO Keyboard & PCB – #TheBrixtyFour Grand Finale" do not show, but the two ones after that do.

This is both looking at the subscriptions feed, and the channel view in Skytube.  I have completely wiped Skytube data and re-imported the XML file from Youtube with the same result.  This may be happening for other channels and I just don't notice.  I have ~54 subscriptions.

I turned off Video Blocker, even though it said it didn't block anything, to see if it made a difference.  It didn't.  I am not using a custom Youtube Data API key, but not sure if that matters.

Any ideas how to figure out what is going on?  I didn't see an IRC channel or anything to see if it is just me or if it's happening to others too.

Thanks!

**Comment by ram-on** [comment]
Hi @ejstacey, use a custom YouTube Data API Key.  This is as shortcuts had to be taken when using a public YouTube API key due to data limits restrictions.

**Comment by ejstacey** [comment]
That appears to have fixed that.  I should have tested with that before bugging you.  Sorry (and thanks!).
