### ISSUE TITLE
Can Info and Comment Icon be made hidable ?

### ISSUE THREAD

**Issue by xtj-9182** [ram-on/SkyTube#40]
Hello, 
so I was wondering if it is possible to make the Info and Comment Icon hidable, since they always seem to be shown and even though they are small they are still overlaying over the video.

**Comment by atomjack** [comment]
I agree. I'm not a fan of those icons showing when you're watching a video. A better plan would be for them to show somehow when you tap on the screen to show the controls.

**Comment by ram-on** [comment]
I agree that a setting can be inserted into the Preferences which allows the user to hide such buttons if explicitly selected.

**Comment by atomjack** [comment]
Wouldn't it make more sense to only show them when the controls show, though? I don't know of any other video player that shows any icons or controls like that - only when you tap the screen to bring up some UI should any controls ever show.

**Comment by ram-on** [comment]
I was thinking about that.  I would like that comments and video desc can be viewed via a swipe.  I also want that functionality to be intuitive and not hidden. Currently when a user taps on the video, the App Bar and Bottom controls will appear.  We can put an info (video desc) icon on top of the bottom bar, however that will look at bit out of place.  Also we can't put those 2 icons in the App Bar as the UI will become cluttered (esp for low res mobile phones).

**Comment by xtj-9182** [comment]
just a thought: 
we could simply add a setting to remove the icons but have it still be swipe-able this way experienced users can hide the icons and new users will see the icons making it intuitive to new users and experienced users alike.

If you can come up with something better that's fine with me too.

**Comment by xtj-9182** [comment]
I came up with a little work around that works for me but might not be good enough for a final version;
so what my changes are doing is that when there is no control element on the screen and you press on the screen the drawer icons will show up and then when you press on the screen again the drawer icons will disappear and the media controls / actionbar will appear if you press on the screen again all controls (including the drawer icons) are hidden and it starts over. Here is the code inside the YouTubePlayerFragment class:

``` java

private boolean areIconsVisible() {
		return isVisible()  &&  (videoDescriptionDrawer.isShown()  ||  commentsDrawer.isShown());
	}

	private void showHud() {
		if (areIconsVisible()) {
			getSupportActionBar().show();
			getSupportActionBar().setTitle(youTubeVideo.getTitle());
			mediaController.show(0);

			videoDescriptionDrawer.close();
			videoDescriptionDrawer.setVisibility(View.INVISIBLE);
			commentsDrawer.close();
			commentsDrawer.setVisibility(View.INVISIBLE);

			// hide UI after a certain timeout (defined in UI_VISIBILITY_TIMEOUT)
			timerHandler = new Handler();
			timerHandler.postDelayed(new Runnable() {
				@Override
				public void run() {
					hideHud();
					timerHandler = null;
				}
			}, HUD_VISIBILITY_TIMEOUT);
		} else {
			videoDescriptionDrawer.setVisibility(View.VISIBLE);
			commentsDrawer.setVisibility(View.VISIBLE);
		}
	}

	private void hideHud() {
		getSupportActionBar().hide();
		mediaController.hide();

		videoDescriptionDrawer.close();
		videoDescriptionDrawer.setVisibility(View.INVISIBLE);
		commentsDrawer.close();
		commentsDrawer.setVisibility(View.INVISIBLE);

		// If there is a timerHandler running, then cancel it (stop it from running).  This way,
		// if the HUD was hidden on the 5th second, and the user reopens the HUD, this code will
		// prevent the HUD to re-disappear 2 seconds after it was displayed (assuming that
		// UI_VISIBILITY_TIMEOUT = 7 seconds).
		if (timerHandler != null) {
			timerHandler.removeCallbacksAndMessages(null);
			timerHandler = null;
		}
	}

```

**Comment by ram-on** [comment]
I'll test your code to see how it behaves.

**Comment by atomjack** [comment]
Hmmmm I haven't tried those changes but I'm not really a fan of having to tap the screen a couple of times. I think it'd be better to just figure out a way to integrate the description/comments controls into the existing UI that has the playback controls. Just my 2 cents.

**Comment by Fatcakes** [comment]
Please ram-on. Those tiny icons ruin the experience.

**Comment by xtj-9182** [comment]
@ram-on 
yeah so if it takes too long to come up with a good long term solution like what @atomjack suggested 
then maybe we could just add a setting to hide them, as has been suggested before, or just use my shitty hacked together code xD. Of course these are only meant as a short term workaround until there is a good long term solution like @atomjack suggested.

**Comment by ram-on** [comment]
Noted.  I comes to me as a surprise that people actually do not like it.  Anyway, I'll see what it can be done.

**Comment by xtj-9182** [comment]
my personal grievance comes from watching videos in the dark, while the icons are tiny they do stick out a lot while watching videos in the dark.

**Comment by ram-on** [comment]
@xtj-9182 So how about if we change the colour of the icons from white to say dark grey?

**Comment by Fatcakes** [comment]
A setting to hide them would be great.

**Comment by xtj-9182** [comment]
@ram-on I often watch videos in portrait mode so making them dark grey would be an improvement. It would still be slightly annoying when watching a video in full screen though.

**Comment by Fatcakes** [comment]
@ram-on would it be possible put the video at the top in portrait mode, and display the comments under the video?

**Comment by ram-on** [comment]
@Fatcakes while that is an option, that would create unnecessary complexity in the code to handle portrait and landscape modes.  The simplest solution is to change the icon colors to gray and give an option to the user to disable the side icons.

**Comment by atomjack** [comment]
I still think the most optimum solution would be to figure out some way to integrate the two buttons into the rest of the UI that shows up that includes the playback buttons, seekbar, etc. I really think the best user experience is for nothing to be on the screen except the video, until tapping, then UI controls can show. 

I mean, it could be as easy as just putting the info button (that appears at the bottom left) directly above the current time display (vertically aligned with the rewind/play/fast forward buttons), and the comments button (top right) on the right side, just a little bit below the bottom of the menu bar that appears (with the back button, video title, restart, and menu buttons). These buttons would only show with the rest of the UI controls.

**Comment by ram-on** [comment]
@atomjack I agree that that might be a good solution for tablets, however I'm a bit concerned regarding small mobile devices (like mobile/cell phone) as not all control buttons may fit in such limited space.  It would be nice if you give it a try on a phone device and demonstrate how it looks.

**Comment by xtj-9182** [comment]
@atomjack I have 2 phones that I could test on if you have any code ready for your suggested improvements.

**Comment by daleylife411** [comment]
Just commenting here that I also would like these two buttons to not always be displayed.

I think pressing on the screen and having the info come up works just fine.

(Of course, Youtube just pushed a UI change where you have to dismiss all the options by pressing an X, which I really dislike.)

**Comment by ram-on** [comment]
FR has now been implemented.  Refer to 69f2a2a6b7a2df530e875aa6872e6b33364a6820:   YouTube player will, from now on, hide the comments and video description icons after a couple of seconds after the HUD is hidden. An option is now implemented in the preferences to disable this behavior (immersive mode).
