### ISSUE TITLE
Bug: videos in dark mode since update

### ISSUE THREAD

**Issue by narayaan** [ram-on/SkyTube#410]
Since updating to the newest version of Skytube extra,  hen trying to play a youtube video it plays it very dark. The app itself has normal lightning, but whenever iI start a video it goes very dark.

Not sure if this is a bug or if I did something wong with the app, but I can't find a solution.

**Comment by ram-on** [comment]
Try to swipe up within the right hand side section of the video player.

**Comment by narayaan** [comment]
This has been solved.
