### ISSUE TITLE
Video Playback Error

### ISSUE THREAD

**Issue by Poomex** [ram-on/SkyTube#416]
Since this morning I can't play any video - I get the message "Video Playback Error - An error has occured while retrieving video's streams."

Same thing happens in NewPipe, it might be due to some changes on YT's side.

**Comment by ChaosKampfkartoffel** [comment]
I have the same Problem. No Video can be played. The  Problem appeared first last night about 0am UTC.

**Comment by ildar** [comment]
NP already fixed

**Comment by SamuelGoldfinger** [comment]
I have the same problem since this morning, so far I have no fix yet.

**Comment by alnixon** [comment]
I built a working version by updating to use the latest NewPipeExtractor.
This subsequently needed changes in HttpDownloader.java to implement the changes to the interface (and a couple of places to pass a new param to NewPipe.init).

**Comment by ram-on** [comment]
Thanks for reporting and thank you @alnixon for the patch - I've added you to the credits.
