### ISSUE TITLE
API key issue

### ISSUE THREAD

**Issue by ByteTemplar** [ram-on/SkyTube#418]
For some odd reason, few days ago my Subcriptions refresh started pulling every video on every channel Ive subscribed. I have 110 subs and now when I do refresh it gets about 4000 videos every single time and mixes em all randomly, so doesnt even show em in time order. 

I removed my custom API key and then it works OK, but doesnt show every video cause there are known limits in default key ofc. If I add my key back, same thing starts happening.

I have installed the new 2.95 version (F-droid) few times now trying different things. Even if I have fresh install and I add my API key and just search any channel, videos are listed in random order? Even if I select a channel from Featured page, it lists the videos randomly, like 5y old is first, then 4y and next is 5y old, suddenly there is 10month old and 5y old again. I hope you get what Im trying to explain :) 

Im totally lost here, isnt anyone else having this problem, when using custom key?

I even created new Google project and API key, tried it and its quota maxed before I could refresh my sub list. It seems Google only gives 10k queries per day now on new projects. My old one has 1mil luckily, but its allready hitting 140k just by testing this.

**Comment by atomjack** [comment]
I'm getting the same thing, it just started happening a couple days ago. Haven't had a chance to research it yet.

**Comment by ejstacey** [comment]
I'm experiencing the same.  I've cleared data+cache and re-set everything up (importing subscriptions from youtube), tried reducing my count of subs to 41 (from 54), tried generating+using a new API key.  Uninstalled and reinstalled (disabling the Google "account data restore" feature when I did it), tried using Skytube instead of Skytube Extra (although that shouldn't matter I think).  Nothing seems to have worked.

**Comment by ByteTemplar** [comment]
Ok, it seems the problem is more wide spread then, hopefully there is somekind  of fix available soon. Cause now the app is basicly unusable for me...

Ive also tried all kinds of things and everything is fine till you add custom API key. So something has been changed on Googles side few days ago, even though nothing has been listed on revision history of the API.

**Comment by atomjack** [comment]
I did some poking around google's issue tracker and found this related thread: https://issuetracker.google.com/issues/128835104

Note comment # 2: "Thank you for bringing this up here. These specific filters have been currently disabled on both YouTube.com and through the APIs. We should have an update on this soon. Thanks again."

**Comment by atomjack** [comment]
Also, to explain why we're seeing this problem when using our own API key versus using the default ones:

Using the API's search functionality is very expensive in terms of quota units (each API key only has a certain number of quota units to spend each day before it's locked for the day). I had found a way to get a list of videos from a channel using a much less expensive way, however for some reason when using this way, not all videos are returned. The way @ram-on and I dealt with it was to have two methods to get a list of videos for a channel - the Lite version and the Full version. When using your own API key, it uses the full version, which uses the API's search functionality. The Lite version (when not using your own API key) uses the less expensive, but not quite as accurate, way of getting videos for a channel. This way, it decreases the chances of the default API keys the app uses (for everyone that isn't using their own API key) get locked.

For some reason google has disabled a bunch of the parameters that the API's search functionality uses. Hopefully we'll learn more soon.

**Comment by ByteTemplar** [comment]
As I also mentioned earlier, you only get 10k queries quota on new API keys you create and that runs out so fast when I was testing. My old one from few years ago has 1 million quota.

So new users might be having problems with it, if they sub to lotsa channels and using own key. 

Hopefully they will tell, why they are disabling some functions and if those are coming back.

**Comment by atomjack** [comment]
Also found this, it seems it's related to them trying to remove graphic content, and it's supposedly temporary: https://www.reddit.com/r/youtube/comments/b1plj5/sort_by_upload_date_not_working/eiojtjh/

**Comment by atomjack** [comment]
Looks like they fixed the filters. I inputted my personal API key and it's not loading every single video anymore. Sorting seems to work properly now, too.

**Comment by ByteTemplar** [comment]
Yes, it seems the problem has been fixed on Youtube's end and everything is working as usual. I will close this issue and hope it will continue to work for now...
