### ISSUE TITLE
Bug: Playing state not persistent

### ISSUE THREAD

**Issue by jugendhacker** [ram-on/SkyTube#429]
If I start to play a video with Skytube and then pause it and switch to another app the Skytube app gets eventually killed because of low RAM. If I then switch back to Skytube it has lost the time/state of the video playing. I think this could be solved by saving the actual video and time position into shared preferences or a database when the app gets into background.

**Comment by gzsombor** [comment]
This is actually implemented, it's not 100% bug free, but in the next release, hopefully it will be fixed.
