### ISSUE TITLE
Google Playstore compatibility Steps

### ISSUE THREAD

**Issue by Divyaadz** [ram-on/SkyTube#433]
To make this app compatible with play store, what all things need to be changed in this app? Removing the download option and adding YouTube API instead of default is enough? Please let me know your input. Thanks

**Comment by atomjack** [comment]
I really don't think that will ever happen, since Google owns YouTube and they probably don't want alternative youtube clients in their store.

@gzsombor you should close this.

**Comment by gzsombor** [comment]
If someone wants to do it, I'm not oppose it, but I'm certainly not interested in putting into the playstore. I guess, they would consider that having multiple Youtube API key in one app, is a suspicious behavior.

**Comment by atomjack** [comment]
Yeah, and I think the only person who should ever make the decision to put SkyTube in the Play Store (if it was even possible) is @ram-on. I'm vehemently against anyone else doing it.
