### ISSUE TITLE
gboard suggested word skyboard keeps stopping

### ISSUE THREAD

**Issue by ZenMasta** [ram-on/SkyTube#439]
Skytube Extra has been crashing often when I tell gboard to use one of the suggested words.

Quite often if happens when I try to swipe type the word `Dota`. 

Often this will be interpreted as `Dora` and then I choose the corrected word that I wanted `Dota` and then the app will crash. It has happened with other words too but I can consistently get it to happen with this particular word.

For what it's worth, my device is a One Plus 7p
OxygenOS 9.5.3
App Version 2.95 Extra

![Screenshot_20190523-093207](https://user-images.githubusercontent.com/823528/58270925-c1d6c400-7d3f-11e9-8f7a-87960ba2e761.jpg)

If there was a way to include debug or log stuff, I would. But at the moment I don't know how.

**Comment by gzsombor** [comment]
It looks very similar to https://github.com/ram-on/SkyTube/issues/439
