### ISSUE TITLE
Add Watch on TV functionality

### ISSUE THREAD

**Issue by Gitoffthelawn** [ram-on/SkyTube#444]
Excellent job on SkyTube!

The one piece of important functionality that it seems to be missing is the ability to watch a video on a WiFi connected TV.  The regular YouTube app does this.  Can SkyTube get this functionality?

**Comment by atomjack** [comment]
I've actually been working for awhile on adding Chromecast functionality to SkyTube. It's pretty much ready, but Ramon hasn't had a chance to merge it in and release it yet. In the meantime, if you'd like to download the code and compile/install it on your Android device yourself, you can find it here: https://github.com/atomjack/SkyTube/tree/chromecast

**Comment by gzsombor** [comment]
https://github.com/ram-on/SkyTube/pull/365 merged, so we can close this issue, thanks for @atomjack !
