### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by dheerajbred** [ram-on/SkyTube#448]
Nothing appears when I open the app. No videos are appearing

**Comment by gzsombor** [comment]
It's pretty hard to guess, what went wrong in your case.

**Comment by webdevsuperfast** [comment]
I had the same issue but with the latest(v2.96) it returns empty(no videos) on load or even when searching, the previous version(v2.95) was loading videos but can't seem to play some videos so I opted to update. I'm using Asus Zenfone Max Pro with Android 9 by the way.

**Comment by gzsombor** [comment]
In this case, it seems that it's a key restriction prevents accessing the Youtube API

**Comment by gzsombor** [comment]
[2.961](https://github.com/ram-on/SkyTube/releases/tag/v2.961) contains the fix for this bug.
