### ISSUE TITLE
Unable to set my custom youtube playlist 

### ISSUE THREAD

**Issue by TrickyAnkit** [ram-on/SkyTube#47]
Unable to set my custom youtube playlist  i have tried almost more than 100 times i have done changes in manifest . Build. gradle api key but still not able to set my custom youtube channel link. Please help ASAP

**Comment by ram-on** [comment]
SkyTube currently cannot play YouTube playlists.  Will be implemented in the future.

**Comment by TrickyAnkit** [comment]
OK thanks for the info. but please do it ASAP!

**Comment by ram-on** [comment]
Playlist is now supported by SkyTube as per @atomjack's PR (#190 and 3617c83). It will be available in the next release.
