### ISSUE TITLE
Many videos don't load (mostly songs)

### ISSUE THREAD

**Issue by Bunnicula2** [ram-on/SkyTube#472]
Over the past few weeks an increasing number of videos, most if not all songs, won't load in SkyTube. Many videos and songs play normally and it all plays in other programs.

Everything works well up until the video screen appears. The app shows the loading circle for a few seconds. After it disappears the pause button is shown for a few seconds, and then it reverts to the play button again. Nothing is played and the screen remains black.

I can restart the whole process by using the restart button in the upper right and sometimes after 5-10 tries it succeeds in playing the song, but I haven't had any luck with that trick lately.

Example of the videos where it happens:
- https://youtu.be/WRq9PzI4_Ow
- https://youtu.be/RKxCJjHmnJg

**Comment by Sigur788** [comment]
I have the same issue I am using samsung galaxy note 8.

Peace.

**Comment by PoorPocketsMcNewHold** [comment]
I can confirm having the same issue, on the galaxy note 8 like @Sigur788 reported, even if i don't think it's hardware related.

**Comment by atomjack** [comment]
Yeah, it's not hardware related, but something about the specific videos. The Newpipe Extractor, which gets the url of the video in order to be able to play it, returns an url for certain videos that returns a 403 (permission denied) error. Not really sure why, or what the solution is :(

**Comment by gzsombor** [comment]
Yes, strange indeed :(

**Comment by gzsombor** [comment]
It seems it is fixed in NewPipeExtractor: https://github.com/TeamNewPipe/NewPipeExtractor/pull/177 and if we bump the version, everything works.
Ironical, I've just went through to create a new release a couple of hours ago...

**Comment by gzsombor** [comment]
[2.961](https://github.com/ram-on/SkyTube/releases/tag/v2.961) contains the fix for this bug.
