### ISSUE TITLE
Crash after updates

### ISSUE THREAD

**Issue by ejstacey** [ram-on/SkyTube#490]
Hi,

I think this might be related to #475, but the error messages don't match, so I thought I'd do it as a new issue.

I have a V20 running Android 8 and Skytube Extra.  Since the new releases (started in 2.96, happens in 2.961 and 2.962), if I have a video playing in fullscreen/immersive mode, and I pull up the navigation bar at the bottom and hit the "square" or "circle" icons which shows me all my open apps in a card style, or takes me to my home screen, Skytube crashes.  I get a message with only "Close app" as an option.  I've crashed it multiple times in testing for this ticket so I get "SkyTube Extra keeps crashing" message right now.  Curiously, sound continues to play a second or two if I leave the crash dialog up and don't hit "Close app" straightaway.  Previous to 2.96, I could navigate elsewhere in my system and Skytube Extra would keep playing the audio in the background/not crash.

I fired up adb and logcat, filtering on 'skytube', and got the attached.  The stuff just before the crash is me pulling up the navigation menu.  The space inbetween the crash message and the rest of the log (the multiple blank lines) is me separating the crash message and what came when I actually clicked "Close app".

[skytube-crash.log](https://github.com/ram-on/SkyTube/files/3480316/skytube-crash.log)

I don't have root on this phone but can do some basic adb stuff if it helps you find the bug.

Thanks,
-Eric

**Comment by atomjack** [comment]
@ejstacey Thanks for the report! This is something I missed when I added Chromecast support.

@gzsombor You can recreate this by doing as he describes, in Skytube Extra - start playing a video (immersive has no bearing on this, actually), then either use the recent apps button or the home button in the navigation bar. See the PR for an explanation of the cause.

**Comment by ejstacey** [comment]
I can confirm this was fixed in the latest release (2.963).  Thanks!
