### ISSUE TITLE
Open YouTube links in SkyTube

### ISSUE THREAD

**Issue by eftas-gka** [ram-on/SkyTube#5]
Just a humble suggestion to allow YouTube links to be opened in Skytube as default app. Great work otherwise!

**Comment by ram-on** [comment]
Thanks.  It will be included in the next release.

**Comment by ram-on** [comment]
Done.

**Comment by apandada1** [comment]
I have a Xiaomi Poco phone. Somehow, when I open an youtube link, it opens witty the youtube app. How do I make SkyTube open the links?
