### ISSUE TITLE
Feed tab refresh broken

### ISSUE THREAD

**Issue by atomjack** [ram-on/SkyTube#513]
Hey @gzsombor your latest [commit](https://github.com/ram-on/SkyTube/commit/f13d4790e94f2f70b269fc38a668c34501aeca0b) breaks refreshing the Feed tab. 

On the feed tab, doing swipe down to refresh just shows the spinner, but not the dialog. Switching to another tab and then back to Feed shows the dialog, but it never goes away, and stays at "Fetched 0 videos from 0/X channels."

**Comment by gzsombor** [comment]
Thanks, I've noticed that today too. I will fix it ASAP, because it droved me crazy during my commute :)

**Comment by atomjack** [comment]
Also, it looks like my changes that added the ability to hide tabs has caused problems with refreshing - it's getting fired off every time I launch the app. I checked it by checking out the last commit I did for that feature, compared to the commit just before that featured was added. So we both messed some stuff up haha.

**Comment by atomjack** [comment]
I think I tracked down the problem. `SubscriptionsFeedFragment.startRefreshTask` shouldn't be called in `SubscriptionsFeedFragment.onResume` unless `shouldRefresh` is true. It's an easy fix, I can push up a PR right away if you'd like.

**Comment by gzsombor** [comment]
Currently I'm testing a similar change, thanks :)

**Comment by atomjack** [comment]
Thanks!!
