### ISSUE TITLE
Appears blank and i can't able to figure it out whats the problem, is there any fix

### ISSUE THREAD

**Issue by rubysm** [ram-on/SkyTube#516]

**Comment by rubysm** [comment]
The app seems empty and doesn't display anything whether the problem is with the latest version or i neet to tinker some settings to make it done... Fix need ASAP

**Comment by atomjack** [comment]
Have you tried generating your own API key?

**Comment by rubysm** [comment]
Howbto do that @atomjack, provide me some instructions

**Comment by atomjack** [comment]
Go to https://console.developers.google.com/apis/, create a project there, and enable the YouTube Data API v3 (via the button in the dashboard section), then go to Credentials, and create a new API key, then use that key it generates in the app (Preferences->Others->YouTube API Key).

**Comment by rubysm** [comment]
@atomjack i have figured it out and applied the key and the contents are fetched but suddenly they all disappears when i clicked subscribe button and i have cleared app data and and also reapplied api key but it ain't back to normal..

**Comment by gzsombor** [comment]
Please try the new version, with the NewPipe backend
