### ISSUE TITLE
Import/Export subscriptions to OPML

### ISSUE THREAD

**Issue by ZaneHannanAU** [ram-on/SkyTube#52]
Mostly for compat between F-Droid ST and STE.

Should also be decently easy:

```xml
<?xml version="1.0" encoding="utf-8"?>
<opml version="1.0">
	<head>
		<title>YouTube subscriptions exported from SkyTube</title>
	</head>
	<body>
		<outline text="YT Channels" title="YT Channels">
			<outline type="rss" text="Google Chrome Developers" title="Google Chrome Developers" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCnUYZLuoy1rq1aVMwx4aTzw"/>
		</outline>
	</body>
</opml>
```

**Comment by ram-on** [comment]
What do you mean by ST and STE?

**Comment by ZaneHannanAU** [comment]
SkyTube & SkyTube Extra

**Comment by ram-on** [comment]
Subscriptions importation and exportation is now supported by SkyTube (version 2.70).  You can even import subscriptions from your YouTube account.

**Comment by evolverine** [comment]
But is there a way to export to text or a format that's readable by other apps? I want to move from SkyTube to NewPipe and I don't know how to export and import my subscriptions.
