### ISSUE TITLE
[Bug] Skytube Search different to YouTube search

### ISSUE THREAD

**Issue by github-throwaway** [ram-on/SkyTube#53]
The Skytube Search is not showing the results the YouTube search is showing:

Doing a search for **"Drugslab"** on my N9005 running Android 5.0 the Skytube app (2.1 and 2.2 Extra) does not list the channel or any of their videos in the results. Trying to access a YouTube link from the channel via Skytube results in an *invalid video URL* error.

**Comment by ram-on** [comment]
This is an interesting bug.

**Comment by github-throwaway** [comment]
Here are two example screenshots.

![screenshot_2017-02-01-22-16-38](https://cloud.githubusercontent.com/assets/25488086/22526662/657a7e0e-e8cc-11e6-82b3-f9425b76422d.png) | ![screenshot_2017-02-01-22-16-16](https://cloud.githubusercontent.com/assets/25488086/22526663/657f30fc-e8cc-11e6-87ac-f6a22ad2e8ad.png)
:-------------------------:|:-------------------------:

**Comment by ram-on** [comment]
Resolved.
