### ISSUE TITLE
Problem to install v2.963

### ISSUE THREAD

**Issue by Guigui3o2oo** [ram-on/SkyTube#539]
Hi,

I can't install Skytube Extra v2.963… on my Samsung Galaxy Note 8 (Android 9). Error message during installation : "App not installed."
I don't have this problem with the v2.95…

Please help.

**Comment by gzsombor** [comment]
Is this happens during upgrade? Or you've uninstalled the previous version?

**Comment by Guigui3o2oo** [comment]
When I use the app for the update or when I download manually the file there is the same error.
I don't have uninstalled the app.

**Comment by gzsombor** [comment]
The problem is that v2.95 is signed by a different key, so Android refuse to simply upgrade to it, you need to uninstall the old version - obviously after you've created a backup of your settings.
