### ISSUE TITLE
[Request] Add search history and history of viewed videos

### ISSUE THREAD

**Issue by xamica** [ram-on/SkyTube#57]
Some time I want to find good videos, which seen some time ago, but I have no idea how I found it. So I spending many time for scrolling all search queries of last time. Search history of history of viewed videos can solve my problem

**Comment by xamica** [comment]
Any work in this area?

**Comment by ram-on** [comment]
Not yet.  It's a low priority FR for now.

> Some time I want to find good videos, which seen some time ago, but I have no idea how I found it.

Regarding the above:  this issue is now resolved due to the bookmarks feature.

**Comment by ram-on** [comment]
Search history implemented as per 8029882522cad25dfe6c09826899dfa481a5eca0.

**Comment by devmsv** [comment]
Hi, would it be possible to have a history tab with all the viewed videos?
