### ISSUE TITLE
[bug] cannot play video after returning from "open with" 

### ISSUE THREAD

**Issue by tingsu** [ram-on/SkyTube#570]
- I have searched the history issue list, and have not found a similar bug. 

- The bug was found on the latest version 2.965 (just released a couple hours agao), and were reproduciable on a Google Plxel 3 and an Android emulator 6.0 device

- Bug: select one video, the video will start playing in the app; select the menu option ``open with`` from the top menu. The user will be navigated to an external app client (e.g., the official Youtube app or a browser) to play this video. When the user navigates back to SkyTube, the original video cannot be played even the ``play`` button is clicked (the ``play`` button will never become a ``pause`` button).  

- Reproducing video 

(1) Reproduce on a Google Plxel 3  (with the official Youtub client installed)

![SkyTube-Extra-2 965-issue-Pixel](https://user-images.githubusercontent.com/3156978/65814795-04754500-e1e7-11e9-8816-5b64382d7571.gif)

(2) Reproduce on an Android emulator 6.0 device (without the official Youtub client, only the default browser)

![SkyTube-Extra-2 965-issue-emulator-6 0](https://user-images.githubusercontent.com/3156978/65814798-0939f900-e1e7-11e9-9108-e0c9a301f7b1.gif)

Thanks for building this interesting app. Hope to see this bug can be fixed soon.

**Comment by gzsombor** [comment]
Thanks for the excellent bug report, it was very helpful to fix the bug!

**Comment by tingsu** [comment]
Thanks for your quick fix @gzsombor !
