### ISSUE TITLE
[bug] inconsistency issue when canceling the video watching if only mobile data on

### ISSUE THREAD

**Issue by tingsu** [ram-on/SkyTube#572]
- I have searched the history issue list, and have not found a similar bug (this reported bug is different from #285). 

- The bug was found in the latest release version 2.965, and were reproduciable on a Google Plxel 3 and an Android emulator 6.0 device

- This bug has inconsistent behaviours.

The environment: Only the mobile data is on; the wifi data is off.

**Test 1**: Under the ``MOST POPULAR`` tab, click one video, the app pops the dialog to ask whether to cancel the watching under mobile data; choose ``Never ask again`` and ``CANCEL``, click the video again, the video **can be** played (*incorrect behavior*).

See the reproducing video:

![SkyTube-Extra-2 965-issue-most-popular-do-not-use-mobile-data-emulator-6 0](https://user-images.githubusercontent.com/3156978/65821518-f0f1ca80-e236-11e9-9656-36e847dc1945.gif)

**Test 2**: Under the ``FEATURED`` tab, click one video, the app pops the dialog to ask whether to cancel the watching under mobile data; choose ``Never ask again`` and ``CANCEL``, click the video again, the video **cannot** be played (*correct behavior*). If we exit this vide, and click another video under the same tab. That video can be replayed (*incorrect behavior*). If we back to the previous video again, the previous still cannot be played (*correct behavior*).

See the reproducing video:

![SkyTube-Extra-2 965-issue-featured-do-not-use-mobile-data-emulator-6 0](https://user-images.githubusercontent.com/3156978/65821570-87be8700-e237-11e9-9df1-327627bdb1bf.gif)

**Comment by gzsombor** [comment]
The 'Never ask again' option is only to silence this warning, but you assume that it means that "Do not play and never allow it in the future". 
I can't reproduce the inconsistency between the various tabs - the only possible explanation for me, that you've already downloaded that video, and that's why the app doesn't show up a warning about mobile data usage.

**Comment by tingsu** [comment]
Hi @gzsombor , thanks for poiting out the design intention of the ``Never ask again`` option. 

Then, I have a question, if the ``Never ask again`` option is selected and then click ``Cancel``, what is the exepcted behavior in the future (for other videos)? Can you explain this more clearly?  Does it mean, in the future, if I select one video, this dialog will not show again, and just play the video under the mobile data OR ... ?

But, anyway, I still observe the inconsistent behaviors about this functionality (see the reproducing video below). Note that **I recreated a fresh new Android 6.0 emulator. I have not downloaded any videos beforehand. This means I just use the app after the fresh start**. 

Step 1: Under the FEATURED tab, click one video (``We had a McDonald's Wedding in Hong Kong`` in my case), the app pops the dialog to ask whether to cancel the watching under mobile data; choose ``Never ask again`` and then ``CANCEL``; click this video again, the video cannot be played (I think this is the correct behavior, meaning the app does not play the video if the user cancel the playing under mobile data).

Step 2: Click another video (``Billie Eilish: Bad Guy (Live)- SNL`` in my case, on the right of the previous video in Step 1) under the same tab. The video now can be played (Again, what is the expected behavior here? I am confused.)

Step 3: Click a third video (``What's inside Nike Joyride Shoes`` in my case, under the video in Step 1), This video cannot be played. (I have never manipulated on this video before, why cannot I play this video? This video and the video in Step 1 are not in the same channel. I have not found any relation between them. It seems the ``Cancel`` option of the video in Step 1 affects this video.)

Step 4: Click the fourth video (``The Billio Ant Mega Colony and ...`` in my case, under the video in Step 3). This video can be played (I have never manipulated on this video before, in this case, why can I play this video?)

- Reprodcuing video

https://youtu.be/wcW0QHgYUhI

**Comment by tingsu** [comment]
Thanks for your quick fix @gzsombor !

**Comment by gzsombor** [comment]
Ok, I've implemented a new feature, so if you switch on the checkbox "Never ask again" _AND_ you click on the Cancel, the from now on, none of the videos will be downloaded over mobile network. I see, the previous behavior was a bit misleading, and this logic actually makes more sense.
 I have to change the preference settings too - so you can change it later, to 'Ask always'/'Block' or 'Allow all'.

**Comment by tingsu** [comment]
Thanks for your change and explanation, @gzsombor . I agree with you that the new feature is more intuitive. I will help on to validate the new features once you are done.
