### ISSUE TITLE
only when the video was played for more than 5 seconds, the video can be resumed.

### ISSUE THREAD

**Issue by tingsu** [ram-on/SkyTube#575]
- I have searched the history issue list, and have not found a similar bug.

- The bug was found in the latest release version 2.965, and were reproduciable on a Google Plxel 3 and an Android emulator 6.0 device

- Bug: click one video, and wait it for playing less than 5 seconds, and exit the video, and click this video again, the video just play from the very beginning and does not show a dialog to alert the user whether to ``Resume`` the video or ``No``.

**Comment by gzsombor** [comment]
This is a feature, not a bug. Clicking on a dialog button, for a question about, if the user would skip, or watch over the first 5 seconds, would be more annoying, and time consuming, than watching it again.

**Comment by tingsu** [comment]
Thanks for your explanation, @gzsombor !
