### ISSUE TITLE
Background play?

### ISSUE THREAD

**Issue by Decme** [ram-on/SkyTube#6]
The audio stops when you switch apps. Can this be fixed?

**Comment by ram-on** [comment]
Currently background play is only supported when you lock your device's screen.  However, this is rather a byproduct of Android's VideoView than an actual feature.

I actually need to research what the TOS states.  I don't want Google blocking my api-key.

**Comment by glitchphan** [comment]
@Decme In the meantime try NetMBuddy from F-Droid. Make sure to manually select the newest version because the older one is starred for some reason.

**Comment by CrisBRM** [comment]
Newpipe does this and it's great. I would definitely switch to skytube if you were to implement this feature.

**Comment by theScrabi** [comment]
@ram-on If google TOS prevent that, we could combine NewPipe an Skytube by sending special Intends. So could add an play in background button, and if NewPipe is installed it will automatically pop up the play-in-background notification.

**Comment by ram-on** [comment]
@theScrabi thanks actually quite interesting.  is such intent already implemented in NewPipe?

**Comment by theScrabi** [comment]
No. Request it and it will come.

**Comment by avently** [comment]
@ram-on is it easy to implement? If yes,can you give us a code? If you don't want your API key to be blocked I will use my own

**Comment by ram-on** [comment]
@Decme Issue fixed and available in the current SkyTube release.  Foreground video playing is now supported.
