### ISSUE TITLE
[Request] Add options for disable autorefresh and return tabs in featured videos

### ISSUE THREAD

**Issue by xamica** [ram-on/SkyTube#60]
I like to have options for disabling this new features.

**Comment by ram-on** [comment]
What do you mean by "return tabs in featured videos"?

**Comment by xamica** [comment]
Style of previous version, when "featured" videos can be selected in combobox, not in tabs. I don't like this new feature in new version. Maybe, you can add checkbox for old style?

**Comment by ram-on** [comment]
No can do.  What its going to be done is that on scroll the app is going to hide the title bar (but the tabs will remain visible).

**Comment by xamica** [comment]
I think, it just waste space on screen, even on small screens. Previous version was better. I understand, you want this tabs, so I ask only about option to disable/hide it.

**Comment by ram-on** [comment]
What am I going to do is to:

- Hide the Title bar (when user scrolls down)
- The tab bar will still remain visible for now.

That way its going to be similar to the old version.

**Comment by ram-on** [comment]
> What am I going to do is to:
> 
>   * Hide the Title bar (when user scrolls down)
>   * The tab bar will still remain visible for now.
> 
> That way its going to be similar to the old version.

The above was implemented.  Refer to 55dc77681a96db94498e4b4b47af6dbc76951ddb.
