### ISSUE TITLE
Unable to set API Key

### ISSUE THREAD

**Issue by jEsuSdA** [ram-on/SkyTube#602]
I was unable to config API KEY in settings.
I tried 3 keys and an error occurred: "error validating api key".

Thanks!

**Comment by gzsombor** [comment]
I guess, you've entered a wrong key - either, because you typed incorrectly, or you've created a wrong key, either not for Youtube API, or you've limited that key to a different app (this could happen, but it's not something, what you could accidentally do)

**Comment by ServisOficial** [comment]
No men, don't close the issue, i have the same problem, i don't care nothing the api is not work :(
https://i.ibb.co/k5sM1LD/Screenshot-2019-12-02-Restringir-y-cambia-API-y-servicios-skytube-Consola-de-API-de-Google.png
