### ISSUE TITLE
create a possibility to make featured and most popular optional

### ISSUE THREAD

**Issue by narayaan** [ram-on/SkyTube#615]
I use Skytube to track the YouTube channels I like. I'm not really interested in seeing generic lists of popular YouTube videos, so I'd love to have a way to turn of the "featured" and "most popular" tabs. This way I'll be able to exlusively focus on the content I love.

**Comment by atomjack** [comment]
You can already do this by going to Preferences->Others->Hide tabs. :)

**Comment by narayaan** [comment]
Wow thanks, I did not know that. Closing the issue.
