### ISSUE TITLE
Add Home feed

### ISSUE THREAD

**Issue by Victor239** [ram-on/SkyTube#616]
Not sure what makes up the home feed when I check it on mobile YouTube but it's different from both YouTube's own Trending and your own Most Popular feeds, with more videos relevant to me.

**Comment by gzsombor** [comment]
Sorry, I don't understand the problem, and what is the 'Home feed'?

**Comment by AWalton** [comment]
If you go to the homepage on YouTube on a mobile browser it shows a variety of videos. This selection of videos is relevant to my interests yet I'm not logged in. I'd like to be able to see this home feed on SkyTube.

**Comment by atomjack** [comment]
You must be logged in (to your google account?) if it's showing you videos relevant to your interests. There's no other way they'd know which videos to show. 

My guess is your mobile browser is logged in to your google account, so visiting youtube from the browser has you logged in. I bet if you tried it in an incognito browser window you'd not see the same videos recommended to you.

**Comment by AWalton** [comment]
Strange, I wasn't logged in yet it still shows me different videos when incognito. Must be a cookies thing. 

Still, I'd like this logged in home feed to be added to SkyTube if possible.

**Comment by gzsombor** [comment]
If you use Chrome, then you can't really logout from Google's services, I believe :wink:
 As SkyTube doesn't collect any data about your usage/preferences, implementing this in the app would be huge task.  
Maybe,with NewPipeExtractor this could be implemented, but that would mean, that you still need to log into Google - to allow Google to collect even more data about you - but I prefer not to do it, I value everyone's privacy more.
