### ISSUE TITLE
Videos sometimes don't play automatically

### ISSUE THREAD

**Issue by OffifialMITX** [ram-on/SkyTube#62]
Sometimes I have to pause the video and then start it, couldn't detect any pattern yet.

**Comment by ram-on** [comment]
Can you provide more info regarding this?

**Comment by OffifialMITX** [comment]
I wish I could, but there is not much I can tell about it.

As I've already mentioned, I can't tell when this happens (maybe it depends on how long the first part is loading - if it takes a while maybe it doesn't play automatically, but I'm not sure).

The only thing more I can tell is that it happens on my phone and my tablet which have both stock Android 5.1.1.

**Comment by OffifialMITX** [comment]
Oh, I actually did find a pattern, it was way easier then I thought - it just happens every time on my tablet. I have no Idea how I could have overseen that...

**Comment by ram-on** [comment]
Cannot replicate this bug even though multiple devices and emulators were used.  Closing it for now.
