### ISSUE TITLE
Increase width of responsive area around the three vertical dots

### ISSUE THREAD

**Issue by Gitoffthelawn** [ram-on/SkyTube#621]
In video listings, each video has 3 vertical dots that access a menu.  Can a little invisible horizontal padding be added to those triple-dot areas to make it easier to access those menus?

I often wind up on the channel's page instead of seeing the menu because I don't hit the triple-dots exactly where required.

**Comment by gzsombor** [comment]
Yes, I have the same experience with the app, unfortunately that part of the UI is pretty crowded.

**Comment by Gitoffthelawn** [comment]
Glad it's not just me.  Most of the time (actually, almost all the time), it seems like there is a lot of empty horizontal space around those dots.  Even a few extra pixels on each side will help.

**Comment by Gitoffthelawn** [comment]
@gzsombor Thank you!
