### ISSUE TITLE
local subscriptions dissappear

### ISSUE THREAD

**Issue by DI555** [ram-on/SkyTube#626]
i always do upgrading to a newer build, but since last uptates (1 or little more, didn't check the subscriptions long time... ) i see that my local subscriptions are dissappeared.
There's only empty places in sides of them.
And when clicking on them , listings appear but without names of channels(((.
2.968

**Comment by gzsombor** [comment]
Have you tried to use the NewPipe backend? It is possible, that due to Youtube API key limitation, your app couldn't fetch the channel informations, and this is why, you can't see the channel names...

**Comment by DI555** [comment]
yes, checkpox is on, ... and i tried with alternative google api key also...((
looks like support of old baseare broken(((, i updated from 2.95 by skipping several build..., 
i'm using and build 'extra' also, there i just imported (due to resign) the backup...and the same result(((,- i see my bookmarks, but all subscriptions are empty(((

**Comment by gzsombor** [comment]
Could you try to subscribe to a new channel?

**Comment by DI555** [comment]
subscribing to new channels is fine, all channels manes ara visible.

even no use of doing so:  go inside 'empty' channel an do unsubscribe then subscibe(((. 'empty' channel just is moving to the end of list...

**Comment by gzsombor** [comment]
Good to hear!

**Comment by DI555** [comment]
> Good to hear!

...  but may be you suggest:
and so, what to do for people who just was making an update of the app....and who got the empty subscription list !???

or even who made a backup ...and did restore that backup from new build... and got an
empty subscription list also !??

**Comment by DI555** [comment]
@gzsombor 
i find one thing probably broke my subscriptions...
i have one or few deleted channels (yes, sometime the big g doing that bad thing ;(, i usually keep it for reason to find it again).
..., so the updatechannels info process could just stuck on that deleted channel and not going to do update for others live channels...
could you please try to do workaround about that?

**Comment by gzsombor** [comment]
That makes sense! Thanks for the hint :+1:

**Comment by Flashwalker** [comment]
Same shit. Subscriptions list empty too. Only skytube icons.
