### ISSUE TITLE
Wrong sorting of videos in feed

### ISSUE THREAD

**Issue by avently** [ram-on/SkyTube#634]
I had Oss build installed and after some version videos stopped loading at feed page (I have my own api key, other pages worked fine). Then I installed Extra version from releases but here videos at feed page sorted in opposite direction. I'm attaching a screenshot. First video on it was made two weeks ago, second video was made 6 days ago.

![Screenshot_20200112-001851_SkyTube_Extra](https://user-images.githubusercontent.com/7953703/72210770-a2102e00-34d1-11ea-9d3b-ba9f048abfce.png)

**Comment by avently** [comment]
@gzsombor any thoughts why it's happening? There is no way to use the app with broken feed

**Comment by gzsombor** [comment]
The app shows the videos in the order of retrieval, instead of the time of the upload. That made the experience a bit less confusing, because NewPipeExtractor can't return exact dates with seconds precision, so it was hard to find the new videos. I mean, I saw the notification 20 new videos found - and I have to dig into the last 100 from the last 2 days to found what happened.
 Yes, it's not the best solution, I'm open for suggestions - and patches :)

**Comment by avently** [comment]
But why you use NewPipe for feed? I have an api key entered for the purpose of load via api

**Comment by gzsombor** [comment]
In that case, the app doesn't use NewPipe, but still the sorting happens with the retrieval time, which is a problem.

**Comment by avently** [comment]
Found a bug that prevented loading of the first video in a channel
https://github.com/ram-on/SkyTube/blob/master/app/src/main/java/free/rm/skytube/businessobjects/YouTube/GetYouTubeVideos.java#L110
Change
`videoIds.toString()`
to
`videoIdsStr.toString()`

Maybe even better to add additionally this line before sending the request (to remove the last `,`):
`if (videoIdsStr.length() > 0) videoIdsStr.setLength(videoIdsStr.length() - 1);`
But it's not required.

And the main problem made me looking to the code:
https://github.com/ram-on/SkyTube/blob/master/app/src/main/java/free/rm/skytube/businessobjects/db/SubscriptionsDb.java#L612

Why don't you want to change 
`COL_RETRIEVAL_TS`
to
`COL_PUBLISH_TS`
?
I made it and my feed works awesome! I can finally use the app to view my subscriptions.

**Comment by gzsombor** [comment]
What an insidious evil typo, you've just found! That could explain the API key usage problem as well. Thanks, that's drived me crazy :smile: 
 
For the COL_RETRIEVAL_TS vs COL_PUBLISH_TS problem - we also need to modify on line 601 to have proper paging.  I'm thinking about adding a new checkbox, which to use, or have to improve the NewPipeExtractor to have a better date parsing.

**Comment by atomjack** [comment]
@gzsombor Is there a reason we can't just change the column on line 601 to the publish timestamp as well? Does the NewPipeBackend way not populate that column?

**Comment by arkdae** [comment]
Please, I hope you can support sorting the videos in the feed by their upload time. Even if the resolution is by the day, I have 348 channels, and they are all completely insorted. I've got some from minutes ago, hours ago, and years ago all jumbled together. How can I possibly find what's been created today, or even this week?

How about sorting by upload day and then within each day, sort by retrieval time?

**Comment by gzsombor** [comment]
I reverted the sorting to use the publish timestamp, hopefully your experience will be better. I fear, that you will still be confused after the app reports you that 'I found 45 new videos', but only display 15 new ones at the top, the rest were mixed into the next 100 videos.  Sorting by upload day and by retrieval time could work somehow, but I fear that the SQL won't be simple - SQLite is not too strong on the query front, our table structure is not the best, and the precision of the saved event times vary a bit - sometimes we've got '5 days ago' (In the format that '2020-03-18 23:05 as not exact date'), sometimes 'at 2020-03-18 23:05'.

 If someone have time and will to improve it, I would love to see - and merge - it :wink:

**Comment by arkdae** [comment]
I think the issue for me was with the very first pull after installing the app and obtaining the list of my channels to populate the feed. In this case, since it starts empty, the list is completely unsorted, and so it would be reasonable to sort by each video's upload date as best as it can be discerned.

But after that first pull, I think it is perfectly fine to sort by download date and time, ensuring subsequent videos all end up at the top of the list.

**Comment by avently** [comment]
Now sorting is fine, thank you. Closing the issue.
