### ISSUE TITLE
NewPipeExtractor update needed

### ISSUE THREAD

**Issue by atomjack** [ram-on/SkyTube#646]
@gzsombor It looks like YouTube changed some stuff that broke NewPipeExtractor. I was unable to play any videos. I tracked it down to [this](https://github.com/TeamNewPipe/NewPipeExtractor/issues/241).

I noticed you're using your own fork of NewPipeExtractor, but I had to switch to a very recent commit from theirs:

`implementation 'com.github.TeamNewPipe.NewPipeExtractor:extractor:ff61e28424d4c12cf1ff8a914f38fcbd406f2b17'`

**Comment by tokenmath** [comment]
Yep

**Comment by gzsombor** [comment]
Thanks, unfortunately currently I'm far from my signing keys, so I can't create a new release as of now, but only at Sunday.
