### ISSUE TITLE
video playback error

### ISSUE THREAD

**Issue by puddingepoch** [ram-on/SkyTube#652]
newpipe is broken, so i downloaded the latest skytube-extra from github and instlaled it on my samsung tab a 2019  

however, i cannot load any videos
i can find no options for getting additional debug info so the picture is the best i can do..

![Screenshot_20200125-104633_SkyTube_Extra](https://user-images.githubusercontent.com/59093378/73124001-07e5c680-3f64-11ea-9671-6410743f2b80.jpg)

**Comment by sibeliusg** [comment]
Same here. Tried Newpipe and it also won't play any video. So appearently YouTube did some API changes

**Comment by puddingepoch** [comment]
Yeah, I also tried the latest newpipe which got updated recently but it won't instal;l on my device. IDK why, got android 9 and arm 64bit

**Comment by Gitoffthelawn** [comment]
I don't know, but the issue and solution may be the same as here: https://github.com/TeamNewPipe/NewPipe/issues/2981

**Comment by gzsombor** [comment]
The latest SkyTube contains the fix from NewPipeExtractor
