### ISSUE TITLE
Unbookmark menuitem slow to respond; video not promptly removed from bookmarks

### ISSUE THREAD

**Issue by Gitoffthelawn** [ram-on/SkyTube#656]
Overall SkyTube is working great.  **Thank you for all your hard work!**

I've noticed that when pressing the Unbookmark menuitem, it can take 5-9 seconds to unbookmark the selected video.  In other words, after tapping the Unbookmark menuitem, the popup menu remains displayed for 5-9 seconds until control is returned to SkyTube.

Also, even after unbookmarking a video (and waiting several minutes), the video often remains in the Bookmarks tab.  Completely stopping the SkyTube process and restarting it often is necessary for the video to be removed from the Bookmarks tab.

I tested this with SkyTube v2.970 on an Android 7 mid-range (by today's standards) device.  SkyTube had about 300 bookmarks (approximate) during testing.

(BTW, if you want me to break this up into 2 issues, just let me know.)

**Comment by gzsombor** [comment]
Good to hear, that SkyTube works for you! It's always good feeling, that I'm not alone with this experience :wink: 
The bookmark tab is very simple, when a bookmark added, or removed, the whole list is re-fetched, re-rendered, so the performance is not great for such a long list of bookmarks, so I'm not entirely suprised

**Comment by Gitoffthelawn** [comment]
Thank you for the improvements!
