### ISSUE TITLE
Remove connection to www.googleapis.com (feature request)

### ISSUE THREAD

**Issue by infinitewaveparticle** [ram-on/SkyTube#658]
After the latest update I can no longer use SkyTube because I block all connections to googleapis.com (and all google domains). Even though I prefer SkyTube to NewPipe I have to use NewPipe now because it doesn't require this connection.

**Comment by gzsombor** [comment]
If you refer to the 2.969 -> 2.970 upgrade, as the latest, then I don't know, what could be your problem, as there was no change in API usage. You can still use the NewPipe backend, which use webscrapeing to gather the information, and not the Youtube API.

**Comment by anshupal257** [comment]
Please tell me which api keys I have to use, as I can only generate YouTube api v3 data key, but in project there are 5 keys, so how to get next 4 keys

**Comment by gzsombor** [comment]
> Please tell me which api keys I have to use, as I can only generate YouTube api v3 data key, but in project there are 5 keys, so how to get next 4 keys

You only need one key, you can enter only one in the UI. The builtin keys are used randomly, so the Google limits are less likely violated.
