### ISSUE TITLE
[Bug] Pull-to-Refresh actually shows very old videos

### ISSUE THREAD

**Issue by xamica** [ram-on/SkyTube#66]
1. Open any channel with many fresh videos
2. Pull-to-refresh
3. You see only videos 2 months and more older
4. Pull-to-refresh again and again
5. You got videos 5+ years

This is very cool thing to scroll large channels, but it NOT refresh. And I want option to disable it.

**Comment by atomjack** [comment]
Ok I can verify that this is indeed present on v2.2, however on the `master` branch, it works fine. It must have been in the original feature and I must have fixed it in one of my subsequent Pull Requests. @ram-on, do you think you're going to release a new version soon from `master`, with Subscriptions and everything else?

**Comment by ram-on** [comment]
@atomjack Although this might be fixed, these is still some issues with the channel fragment.  For example, I'm subscribed to Zepherus channel:  even though this channel has videos, SkyTube thinks that there are no videos.

Before we can release the next release, we need to fix the recently introduce bugs.  The sooner these are fixed the better.

**Comment by atomjack** [comment]
@ram-on I looked into this, and for some reason the YouTube Data API is not returning any uploads (in the Activities List) for this channel. Very strange, as it appears to work for every other channel I've tried. Do you know of any other channels that are not showing any videos? As far as I know it should list any uploads, which is what those videos are.

If you'd like to try it, the channel ID you need to pass on https://developers.google.com/youtube/v3/docs/activities/list#try-it is UC-x0TtqNsBBQAQzFLnKZHnw

I can submit a bug report, but I'd like to see if you've noticed this for any other channels first.

**Comment by ram-on** [comment]
@atomjack ijustine channel on displays the videos of the last 1 month.  Its very strange.

**Comment by atomjack** [comment]
@ram-on I just checked the ijustine channel on master and it displays the most recent videos as you'd expect, no matter how many times I refresh. Is this happening for you on master? Or 2.2?

**Comment by ram-on** [comment]
@atomjack It is replicable on version 2.2.

**Comment by ram-on** [comment]
@atomjack Just to clarify:  ijustine channel is only displaying (at most) videos that are 1 month old; i.e. if you scroll down, the app is unable to get older videos.

**Comment by ram-on** [comment]
@atomjack The channel "Primitave Technology" is also now showing any videos.

**Comment by ram-on** [comment]
Reported the bug to YouTube/Google:  https://issuetracker.google.com/issues/35553086

Issue resolved by reverting to the old code until they resolve the issue.
