### ISSUE TITLE
Wrong language code for Indonesian

### ISSUE THREAD

**Issue by zmni** [ram-on/SkyTube#660]
For compatibility reason, android is stuck on using legacy old and deprecate language code for Indonesian. `in` is the correct code.

Can you please rename `id` to `in`?

Thank you.

Reference:
1. AOSP source code
2. https://developer.android.com/reference/java/util/Locale#legacy-language-codes

**Comment by gzsombor** [comment]
Sorry for late reply, it's not clear, what's the behavior which you see with the app? You have your Android set to Indonesian, but SkyTube doesn't show up in Indonesian? Is this problem could be Android version specific? So, maybe, if we change 'id' to 'in', maybe it will break it for older Androids?

**Comment by zmni** [comment]
> What's the behavior which you see with the app?

The app does not translated to Indonesian, keep using english.

> You have your Android set to Indonesian, but SkyTube doesn't show up in Indonesian?

Yes.

> Is this problem could be Android version specific?

No. Since the beginning, Android always use `in` for Indonesian language, not `id`.

> So, maybe, if we change 'id' to 'in', maybe it will break it for older Androids?

It will correct this issue.

Some developers handle this legacy language code differently. AOSP only use `in`. NewPipe only use `in` for Indonesian and symlink the other legacy languages. SimpleMobileTools keep them both. F-Droid client symlink the new locale to the legacy one.

**Comment by gzsombor** [comment]
Thanks for the explanation. I hope this change will solve the issue.
