### ISSUE TITLE
Video Parsing Error

### ISSUE THREAD

**Issue by Sploof99** [ram-on/SkyTube#68]
Certain videos only return parsing errors when trying to watch them on version 2.2; this wasn't happening on the previous version. [Example.](https://www.youtube.com/watch?v=PiNdcBg3xC8) Some channels, like [Escapist](https://www.youtube.com/user/TheEscapistMagazine) will have this error on nearly all of their videos.

**Comment by ram-on** [comment]
Hello @Sploof99 Can you please quote the error message?  Or post a screenshot perhaps?

**Comment by Sploof99** [comment]
lI'm unable to upload a screenshot right now, but the error shows up as a plain white box with the header "Play Video Error," and under that, "Parsing Error."

**Comment by Monojerry** [comment]
I also have a parsing error in certain videos.

**Comment by Sploof99** [comment]
[Here's a screenshot of the error.](http://i.imgur.com/HllYdn8.jpg)

**Comment by Monojerry** [comment]
Problems with copyright-related metadata parsing? (e.g. music video)

**Comment by avently** [comment]
[SkyTube.txt](https://github.com/ram-on/SkyTube/files/777944/SkyTube.txt)
Did it help?

**Comment by ram-on** [comment]
@avently thx.  I'll look into it very soon.

**Comment by ram-on** [comment]
Bug resolved (refer to commit 6319cea09bdce6ad4ffcb1646a59b52590918b5e).  Thanks for reporting it.
