### ISSUE TITLE
[Request] Allow sharing by e-mail

### ISSUE THREAD

**Issue by jEsuSdA** [ram-on/SkyTube#70]
It will be nice to allow sharing a Youtube video link by e-mail.

Nowadays I must to open the video on the web browser and then share the url by e-mail. ;)

**Comment by atomjack** [comment]
This functionality is included in #41. I imagine it will be in the next release.

(You will be able to share a video, which uses Android's standard sharing prompt, so you will be able to choose your Email client)

**Comment by jEsuSdA** [comment]
Great!
That are great news!

Thanks a lot for your work and efforts. Cheers! ;)
