### ISSUE TITLE
Improvement on data backup

### ISSUE THREAD

**Issue by okan35** [ram-on/SkyTube#700]
As I just updated to new version, I saw that I had to add my YouTube api key manually while we can also save this data in the backup plus any other setting that can be saved on backup and when we import a backup we can have all the settings from previous version.

Also in backup we need to use automatic restart button like we do in other places in app instead of doing it manually.

**Comment by gzsombor** [comment]
Yes, that's a good point. However, regular users - who doesn't use custom builds - just use the provided upgrades, doesn't have this problem, as the preferences are persisted during upgrades.
But setting the app in different devices, or using the same config for the OSS/Extra versions would be indeed nice.

**Comment by okan35** [comment]
oh I would like this feature because for me update gave app not installed error, Dont know if it is key error or what. So that is why I would like to have this.

**Comment by hyvbgg** [comment]
It would also be great to save the downloaded videos list

**Comment by gzsombor** [comment]
This is implemented and released in v2.973
