### ISSUE TITLE
Fatal crash - NullPointerException - Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setVisibility(int)' on a null object reference

### ISSUE THREAD

**Issue by tingsu** [ram-on/SkyTube#704]
The bug was found in the version 2.97.

It is not easy for me to provide the bug-triggering event trace because my tool generates random tests. Hope the crash stack can help locate the root cause. The crash was triggered multiple times. From the error message, it indicates the app tried to access some destroyed object when it returns from a background thread. The solution should be adding some null checking.

```
FATAL EXCEPTION: main
 Process: free.rm.skytube.extra, PID: 8410
 java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setVisibility(int)' on a null object reference
 	at free.rm.skytube.gui.fragments.BookmarksFragment$PopulateBookmarksTask.onPostExecute(BookmarksFragment.java:117)
 	at free.rm.skytube.gui.fragments.BookmarksFragment$PopulateBookmarksTask.onPostExecute(BookmarksFragment.java:102)
 	at android.os.AsyncTask.finish(AsyncTask.java:651)
 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by gzsombor** [comment]
Thanks for the report, I think your analysis was correct !

**Comment by tingsu** [comment]
Thanks for your quick fix, @gzsombor !  I manually analyzed a lot of Android app crashes before, so I may have sort of insight by looking at the stack trace.  I will continuie to contribute to your app :)

**Comment by gzsombor** [comment]
What is the tool, which triggers this kind of bugs? Are you just very fast and lucky to click that fast? :smile:

**Comment by tingsu** [comment]
In fact, I am developping an automated Android app testing tool that aims to fully automatically find functional bugs (i.e. those bugs that will not trigger any crashes but break the intended app functionality). We am reaching this goal.

These crashing bugs I reported were found during the functional testing process. The tool does NOT send very quick events to the app (Android's own Monkey does this way). In fact, all these reported crashes bugs have very short logged event traces (less than 15 user events).  Before reporting these issues, I usually try to reproduce these issues to make sure the bug reports are useful, straightforward to you :) 

I personally use SkyTube a lot and like this app, so I am working on this app and  hoping to make the app better!

**Comment by gzsombor** [comment]
Really interesting! How can your tool fully automatically detect if a functionality is not expected? Maybe, it's just a special corner case - something like, that since 2.971 shows channels and playlists in the search results - in a bit different boxes. It could be classified as a functional bug, by your tool, couldn't be?

**Comment by tingsu** [comment]
En, this is an interesting question! I will take a close look at the special case you mentioned. As for my tool, one thing is clear if the functional bugs only appear between two different app versions, we cannot detect. I currently focus on functional bugs that appear in one specific version.
