### ISSUE TITLE
Skytube and Skytube Extra showing error

### ISSUE THREAD

**Issue by androidPandroid** [ram-on/SkyTube#709]
![20200327_202034](https://user-images.githubusercontent.com/62744165/77741110-12a20200-7060-11ea-933a-eb7eb03c896d.jpg)

This is shown when you turn on Skytube on Android 9.0 Samsung phone and click to change tabs and check comments.

It is showing in latest version i download today. Sometimes it shows sometimes doesn't

**Comment by androidPandroid** [comment]
It is latest version i download today

**Comment by gzsombor** [comment]
SkyTube has a couple of API key - and picks one randomly for each call. 
I don't know what happened with this key, why it's not working anymore...

**Comment by damascene** [comment]
I'm having the same issue and I've been having similar one since I've installed SkyTube, it rarely works because of this error.

**Comment by yhutoo** [comment]
For me too, in several versions, from 2.82 to 2.970 now, pop up err msgs. Same in latest 2 versions 2.971, 2.972.
Also "Enter Video URL" obstinately proposes some text I copied in an another app; no way to delete it, not deteting all apps cache, not even reinstalling with Asus Backup. Same in two identical ASUS ZenFone 3, Android 6.0.1.
Tks, best.

**Comment by gzsombor** [comment]
This error is fixed in v2.973 - the keys are recreated, and the default behavior is to use the NewPipe backend, which doesn't use Youtube API keys.
