### ISSUE TITLE
Auto-rotate video when playing, even if device's auto-rotation is off

### ISSUE THREAD

**Issue by waqas** [ram-on/SkyTube#73]
I always keep auto-rotation off to avoid accidental app layout changes, but when playing video, it should auto-rotate regardless, just like VLC does.

**Comment by ram-on** [comment]
Similar to #13.  Most probably I'll add a button to the UI so that users can manually rotate video.

**Comment by xamica** [comment]
NO, this most annoying feature in original youtube client! If I forbid rotation in options, I don't to rotate it. If you do this feature, I request option to DISABLE it.

**Comment by ram-on** [comment]
Resolved as per 43826527cfbfc0d882e1bb8d2a8f12003ed10f0b.
