### ISSUE TITLE
Playlists dont show up on playlist tab

### ISSUE THREAD

**Issue by okan35** [ram-on/SkyTube#730]
Title says it. I don't see any playlists of channels in channel playlist tab.

**Comment by gzsombor** [comment]
Do you see any exceptions in the log? The playlists are still queried with the Youtube API, maybe just quota limit ...

**Comment by okan35** [comment]
yeah if you dont set your own YouTube api key even if you use newpipe backend it gives usage limit error but I think we should at least show a warning to user so user knows what is going on.

**Comment by gzsombor** [comment]
Yes, definitely!
