### ISSUE TITLE
Video description totally unformatted, links in description are unusable

### ISSUE THREAD

**Issue by frudolph77** [ram-on/SkyTube#731]
Since video description is fetched directly from NewPipe it's totally unformatted and the links in the description sometimes are unusable.

NewPipe is shortening the links for some reason. They are working fine in the description in NewPipe but not in SkyTube Extra 2.791

See screenshots, they are all showing the same video

### NewPipe
![Screenshot_newpipe](https://user-images.githubusercontent.com/63302676/78688876-033f7600-78f6-11ea-9c99-7d38e91aad7a.png)
See the shortened link in the middle of the description.

### SkyTube 2.970
![Screenshot_skytube](https://user-images.githubusercontent.com/63302676/78688882-05a1d000-78f6-11ea-929e-32206a4c0e80.png)

### SkyTube Extra 2.791
In this example the link in the middle of the description is working.
![Screenshot_skytube-extra_2 971](https://user-images.githubusercontent.com/63302676/78688891-06d2fd00-78f6-11ea-9e1e-e37f65d69d23.png)

**Other Video with totally broken links**
![Screenshot_broken_links](https://user-images.githubusercontent.com/63302676/78690213-75fd2100-78f7-11ea-8fba-f49187a8f49d.png)

### EDIT:
See here the well formatted screenshot from NewPipe. As you can see the URLs you are parsing are broken in some time. All links which are directly followed by a line break, are faulty. 

![Screenshot_links_ok](https://user-images.githubusercontent.com/63302676/78758227-1433ca00-797e-11ea-8434-8dabfb0ebfc3.png)

**Comment by gzsombor** [comment]
Yes,  SkyTube, after gets the description, with Jsoup, cleans the html (I mean, every html tag is removed, links, line brakes, etc), and the text content is parsed for URLs. 
Interestingly, Youtube generates links, where the text content part is trimmed, for example:
`Download the Free Serif font here: <a href="https://logosbynick.com/design-vintage-style-logo-inkscape/">https://logosbynick.com/design-vintag...</a>`

The cleanup process needs to be improved a bit.

**Comment by frudolph77** [comment]
For what reason, do you cleanup the html.

The video creator has provided a pretty well formatted description, which in my opinion should not be changed. Any reformatting will lead to a less readable description.

If you'd like I cloud provide some other screens with unreadable description.

**Comment by gzsombor** [comment]
Because of historical reasons: Youtube API returns the description as plain text - so that text was parsed for links. On the other hand, NewPipe returns as html, and to behave compatible with the original codes, this html was converted to text in SkyTube - basically all the original html tag was removed.
