### ISSUE TITLE
SkyTube plays only the first video of a playlist

### ISSUE THREAD

**Issue by rootkea** [ram-on/SkyTube#760]
I'm using SkyTube 2.972 on LineageOs 16.

When I try to play the playlist SkyTube just plays the first video of the playlist and stops. I have to manually click each video from the playlist to play it.

SkyTube should play the videos from the playlist sequentially (or randomly for "random" mode) on its own without needing any further interaction.

Thanks!

**Comment by gzsombor** [comment]
I think, this is a duplicate request for #413 (and #648 )
