### ISSUE TITLE
Samsung Game Laucher detects skytube extra as game.

### ISSUE THREAD

**Issue by the4anoni** [ram-on/SkyTube#764]
Like in topic. Even if I remove skytube from list of games it is still optimized by Samsung game booster.
![Screenshot_20200529-101028_Game Launcher](https://user-images.githubusercontent.com/13403084/83237121-f839f100-a194-11ea-8374-39113ef2ad7b.png)

**Comment by gzsombor** [comment]
Do you know, how this launcher detects if an app is a game or not?

**Comment by the4anoni** [comment]
> Do you know, how this launcher detects if an app is a game or not?

No, I don't know this.

**Comment by gzsombor** [comment]
And what does it mean, that it's "optimized by Samsung game booster"? What happens with the application? Do you see any problem with it's functionality? Or your device behaves differently?

**Comment by the4anoni** [comment]
> And what does it mean, that it's "optimized by Samsung game booster"? What happens with the application? Do you see any problem with it's functionality? Or your device behaves differently?

Game booster can increase cpu/gpu clocks and etc, this may cause battery drain.

**Comment by gzsombor** [comment]
I see. I don't think that there is anything, which can be fixed in SkyTube, as you are complaining about Samsung game booster's behaviour.

**Comment by drogga** [comment]
Only the "Extra" is detected as a game, the Game Tools (if enabled) are active on this and I have to enable the fullscreen switch toggle so it can extend to the screen's aspect ratio when it's not standard 16:9, because otherwise SkyTube is shown with black bars.

**Comment by drogga** [comment]
#1042

**Comment by warp123** [comment]
There is a work around to remove the app from game launcher manually, by selecting "my games" > three dots > Add game, and from the list you can remove Skytube. 
So after that it does not appear inside game launcher and I assume that game launcher stops optimizing the app. 
Apart from this the default behavior is to recognize it as a game. As mentioned.
