### ISSUE TITLE
[Request] Add notification to Subscription Icon

### ISSUE THREAD

**Issue by github-throwaway** [ram-on/SkyTube#77]
**This might be irrelevant, if you introduce a subscription tab.** I was reading something like this a couples of days back.

However, if you don't plan on this, I would suggest to add a Netflix-styled notification icon, if any any new videos are uploaded to your subscriptions. See Example below:

![20170209_164502](https://cloud.githubusercontent.com/assets/25488086/22865463/8582d844-f165-11e6-8dd9-9a65ba818a93.png)

**Comment by ram-on** [comment]
That side menu will most probably be removed and replaced by a tab in order to increase visibility to that functionality.
