### ISSUE TITLE
Make SkyTube resizable

### ISSUE THREAD

**Issue by alexanderadam** [ram-on/SkyTube#776]
I'm using [Samsung DeX](https://www.samsung.com/us/explore/dex/), which gives a desktop like experience and makes use of Android windowing support.

[Samsung has documentation on how to enable window resizing for Android applications](https://developer.samsung.com/samsung-dex/modify-optimizing.html):

```xml
<application
    android:resizeableActivity="true">
</application>
```

This documentation also has more tweaks and information on how to improve the desktop experience in case you're interested.
They also have [an app testing guide](https://developer.samsung.com/samsung-dex/testing.html) (although some apps are fine with this guide but won't work on "real" DeX sometimes).

At the moment the resizing button is greyed out and the application is always nearly squarish:
![Screenshot of SkyTube on Samsung DeX](https://user-images.githubusercontent.com/372620/88276729-d619a680-ccdf-11ea-9256-0d05135b0178.jpg)

**PS:** I know that it is possible to _force_ all apps to be resizable via `Samsung Labs` > `Force Resize` but it would obviously better to make the application natively resizable to create less friction.

**Comment by gzsombor** [comment]
Interesting idea, adding that 3 lines of xml to the manifest file doesn't seem to be hard, however if there are other subtle bugs triggered by resize, that would be harder to fix - without hardware to test.

**Comment by alexanderadam** [comment]
> if there are other subtle bugs triggered by resize, that would be harder to fix - without hardware to test

I can test APKs if there are any.

**Comment by gzsombor** [comment]
You can download a build from https://github.com/ram-on/SkyTube/pull/782/checks (in the corner, under the Artifacts menuitem). Unfortunately, as it is signed with a different key, than the regular release, you can't simply upgrade on your device. So I suggest you, that if you use SkyTube Extra on your device, download the SkyTube-OSS version, or vice-verse. So you can have 2 different SkyTube app on your phone.

**Comment by alexanderadam** [comment]
@gzsombor so I just tested the release and it works perfectly! :+1:

**Comment by gzsombor** [comment]
Glad, that it worked! Thanks for the links to the docs and to the code examples, it was a big help :smile:
