### ISSUE TITLE
Trouble with search 

### ISSUE THREAD

**Issue by Pjaszewski** [ram-on/SkyTube#777]
I'm recently having trouble with the search. If I try searching for anything, the attached error comes up. I'm on a Oneplus 6 running Android 10. Thank you! 

![Screenshot_20200725-092449](https://user-images.githubusercontent.com/68781738/88459217-51eb2e80-ce59-11ea-8902-ce72c3977e44.jpg)

**Comment by VeteranCoder** [comment]
I am also having this problem since the most recent release. I'm using Galaxy Tab 10.1 T510. On a custom ROM based on lineage OS. I also get it on my Google pixel 2 XL using a custom AOSP based ROM.

**Comment by gzsombor** [comment]
I've noticed too, I guess, the site has changed - I hope a newer NewPipeExtractor could handle it better.

**Comment by arkdae** [comment]
I've been having the same problem. NewPipe doesn't have a problem searching YouTube.

**Comment by gzsombor** [comment]
You can test with the latest build: https://github.com/ram-on/SkyTube/runs/916992627 
Unfortunately, it's signed with a different key (by github), so you can't simple upgrade on your device.

**Comment by Pjaszewski** [comment]
That worked great for me!  Thank you for sharing this new build!.

**Comment by Kukulkan2019** [comment]
Same error report here, just installed latest version from F-droid, new pipe isn't working either even the 0.19.7 version, that's why I tried skytube...

**Comment by serixscorpio** [comment]
> You can test with the latest build: https://github.com/ram-on/SkyTube/runs/916992627
> Unfortunately, it's signed with a different key (by github), so you can't simple upgrade on your device.

Worked for me too!

**Comment by gzsombor** [comment]
This error is fixed in v2.973
