### ISSUE TITLE
0 new videos from subscribed channels

### ISSUE THREAD

**Issue by gitmatt19** [ram-on/SkyTube#784]
As of a couple days ago I am seeing the "0 new videos from subscribed channels"  when updating on the "feed" page even though I see data being downloaded and know there are new videos.

**Comment by gitmatt19** [comment]
If you got an individual feed from the sidebar it will update with new videos and then you will see that update in the main feed list.

**Comment by n-buna404** [comment]
Hi I think this is related to #777 . You can try the test build https://github.com/ram-on/SkyTube/runs/916992627 and give feedback before stable release. It fixes these problems for my device on android 4.1.

**Comment by gitmatt19** [comment]
Yes this seems to have fixed both the Updates not showing and the "Video Playback" error.

**Comment by gzsombor** [comment]
Yes, unfortunately I can't release a new version as of now to fix these issue, and I'm as frustrated as - probably - you

**Comment by gzsombor** [comment]
This error is fixed in v2.973
