### ISSUE TITLE
Video Playback error

### ISSUE THREAD

**Issue by gitmatt19** [ram-on/SkyTube#785]
As of a couple days ago seeing "Video Playback error" an error has occurred while retrieving video stream.
This happens on both Android 4.4 and 6.0.

Sharing a video to Kodi still works and plays fine on the network and playing the video in the android firefox browser still works.

**Comment by gzsombor** [comment]
Related to #777  and #784

**Comment by gzsombor** [comment]
This error is fixed in v2.973
