### ISSUE TITLE
How do I bookmark a video?

### ISSUE THREAD

**Issue by MadMaverick9** [ram-on/SkyTube#79]
I now see the "Bookmarks" tab when I open SkyTube 2.3.

But when I play a video, the menu still only shows "Open with...".

I don't see a menu item to add the current playing video to the bookmarks.

And it would be nice to have a "Copy URL" menu item as well to copy the url of the current playing video to the clipboard.

Thank you.

**Comment by atomjack** [comment]
You bookmark a video from within the app itself:

![screenshot](http://i.imgur.com/GBIprbE.png)

When you say "Open with...", where are you seeing that? When you click the link to a youtube video from another app (like a browser)?

**Comment by MadMaverick9** [comment]
> You bookmark a video from within the app itself:

Oh - Ok. Not really where I was expecting it. Thank you.

The screen where the video is played, is within the app also. No?

> When you say "Open with...", where are you seeing that?

1. Run SkyTube
2. Open video
3. Press Menu Button and see menu with only "Open with..."

All within SkyTube. No other app involved.

**Comment by ram-on** [comment]
@MadMaverick9 Such feature will be added for the next release.

**Comment by MadMaverick9** [comment]
This can be closed.
See [Bug 85](https://github.com/ram-on/SkyTube/issues/85).
