### ISSUE TITLE
[Bug] Videos always play in high quality, even when the resolution is low

### ISSUE THREAD

**Issue by astarq** [ram-on/SkyTube#793]

**Comment by yougoog** [comment]
+1

**Comment by gzsombor** [comment]
You can set the video quality as you prefered

**Comment by astarq** [comment]
I know but changing the quality in settings doesn't work, the quality always stays the same

**Comment by gzsombor** [comment]
The last (v2.976) release had some improvements on the video quality selection logic, it would be nice, if you could retest it, and add more details, how can you still reproduce.
