### ISSUE TITLE
More selectable Default Tabs than in the GUI

### ISSUE THREAD

**Issue by anoymouserver** [ram-on/SkyTube#80]
Under Preferences → Other you can choose between 4 default tabs, but there are only 3 in the GUI.
If you select the 3rd (`Subscriptions`) or the 4th (`Saved`) it will be always selected the last tab in the GUI.

**Comment by ram-on** [comment]
Fixed.  Refer to commit 8d0dd552b9c6bb014fd8031c5e7bcf687a64ece2.
