### ISSUE TITLE
www.googleapis.com error still happens on startup

### ISSUE THREAD

**Issue by infinitewaveparticle** [ram-on/SkyTube#802]
From #658 

After the latest update I can no longer use SkyTube because I block all connections to googleapis.com (and all google domains). Even though I prefer SkyTube to NewPipe I have to use NewPipe now because it doesn't require this connection.

Edit (added today):

When using a firewall to block all googleapis.com connections, on app startup, even the very latest version of SkyTube reports an error about not being able to connect to "www.googleapis.com" - try it. I promise you it happens. Additionally, unblocking googleapis.com allows www.googleapis.com to be shown as a successful connection by SkyTube. This may be related to one of the tabs. I'm not sure, but the app is unusable unless I unblock it. I'd like to use it without unblocking it.

<details><summary>Screenshot:</summary>

![6016330230513049039](https://user-images.githubusercontent.com/29090831/91652721-ddaf3680-ea67-11ea-980f-30147feb49e7.jpg)

</details>

**Comment by gzsombor** [comment]
So the featured and most popular tab are not working for you, am I understand you correctly?

I've tried out, what happens after blocking googleapis.com, the app stayed usuable for me, yes, that two tabs does not show anything, but this is expected.

**Comment by infinitewaveparticle** [comment]
yes, that is correct... however this does not happen with the NewPipe app. the only thing that fails in newpipe is autocomplete because it uses suggestqueries.googleapis.com. search still works. Those featured/popular iterations still load in newpipe. I consider those tabs to be vital to the overall app usage for me.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by gzsombor** [comment]
The most popular tab were implemented with NewPipe, for the other, it uses a custom Youtube API query, which I don't think it is possible to execute with NewPipe
