### ISSUE TITLE
Search outputs error: Could not get ytInitialData

### ISSUE THREAD

**Issue by bluesatoshi** [ram-on/SkyTube#818]
![Screenshot_20201023-125016_SkyTube Extra](https://user-images.githubusercontent.com/7751569/97048129-c9029280-152e-11eb-8be1-2ac6afce6d89.jpg)
NewPipe had a similar problem recently but they've since fixed it. I'm assuming YouTube had some sort of API update or something because right now attempting to search for anything only yields that error.

**Comment by gitmatt19** [comment]
I am seeing the same issue.

**Comment by gzsombor** [comment]
It's already fixed in git

**Comment by gzsombor** [comment]
However, there is another Youtube change, which brakes the NewPipeExtractor - reported here: https://github.com/TeamNewPipe/NewPipe/issues/4572 and https://github.com/TeamNewPipe/NewPipeExtractor/issues/439

I will create a new release, when these could be fixed.

**Comment by gitmatt19** [comment]
Probably all related, starting today Video will not play anymore ("Video Playback Error")and Feed tab refresh does not update with new videos. Updates to a single channel works still.

**Comment by kevjonesin** [comment]
> Probably all related, starting today Video will not play anymore ("Video Playback Error")and Feed tab refresh does not update with new videos. Updates to a single channel works still.

Am experiencing similar. I wonder if these issues having arisen soon after the takedown of youtube-dl might be significant? Like, might challenges arising now for 3rd party apps exemplify to some degree intentional strategy on Google's part rather than just inadvertent effect?

**Comment by gzsombor** [comment]
youtube-dl is removed because of RIA claims and because Microsoft must comply to the US law. I'm sure, that changes in the html/js in the youtube site is not related to this :wink:
