### ISSUE TITLE
Age restriction video not possible in latest update

### ISSUE THREAD

**Issue by prasumoholkar** [ram-on/SkyTube#829]
It would be nice if we get age restriction video in upcoming update.

**Comment by gzsombor** [comment]
In which video have you encountered the issue?
The app uses NewPipeExtractor to actually get the video content, so it is possible, that there were changes in Youtube, which prevents parsing the site for the URL - so in the end, this needs to be implemented in NewPipeExtractor.

**Comment by prasumoholkar** [comment]
I confirmed that same isaue in New pipe latest app,and New pipe will fix in next update.

I hope after newpipe fixes this we get it in skytube too.

**Comment by gzsombor** [comment]
Could you tell me, what is the relevant NewPipe bug?

**Comment by prasumoholkar** [comment]
Age restriction video on latest slytube extra and latest stable Newpipe not playable.

As skytube extra use same api as Newpipe app.

So we get error while playing video that please sign in to continue.

And New beta release of Newpipe fixed this isaue but Our skytube extra still facing issue.

Please update app.

**Comment by gzsombor** [comment]
Could you please answer my questions?
* In which video have you encountered the issue?
* Could you tell me, what is the relevant NewPipe bug? Because I haven't found any recent commit, which mentions parsing videos with age restriction.

**Comment by prasumoholkar** [comment]
Shearing such link feeling odd but u can find any Videos such as Ftv videos on which following error got.

There are tonn of videos on which this error found.

Today new pipe app update with fixes this bug.

On new pipe this age restriction thread is found on 2-3 page as this issue getting old.



![Screenshot_20201119-055133](https://user-images.githubusercontent.com/73677281/99604376-5a303080-2a2b-11eb-8ecc-9d917631fdca.png)

**Comment by prasumoholkar** [comment]
Just tried with reinstall app and now issue solved.

Thanks
