### ISSUE TITLE
Crash if impossible to subscribe to a channel

### ISSUE THREAD

**Issue by Bolsderac** [ram-on/SkyTube#834]
Hi,

An exemple with some screenshots

![Screenshot_20201114-142715](https://user-images.githubusercontent.com/60016981/99148111-3913bc80-2686-11eb-8479-49611800dd5a.jpg)

![Screenshot_20201114-142657](https://user-images.githubusercontent.com/60016981/99148117-403aca80-2686-11eb-8a4f-134c52884ca0.jpg)

Arnaud

**Comment by gzsombor** [comment]
Thanks for the report!
