### ISSUE TITLE
Ability to import subscriptions via a .json file 

### ISSUE THREAD

**Issue by vanillaneutrino** [ram-on/SkyTube#838]
Hi, is there a way of importing subscriptions via a .json from google takeout? The original method of exporting subscriptions from youtube does not work anymore. Thanks
Thanks.

**Comment by profucius** [comment]
Second this. Google changed their Youtube website to no longer allow exporting subscriptions using the old method. The only way to export subscriptions now is to use Google Takeout and export them as a .JSON file. Please update your app to import using this format.

**Comment by gzsombor** [comment]
Contributions are always welcomed, unfortunately even if I could work on SkyTube 8 hours a day for the next months, I couldn't implement all the feature requests alone, to address the 138 open issue in this tracker.

**Comment by profucius** [comment]
No worries, I will switch to NewPipe in the meantime, which has resolved this issue in their latest version.

**Comment by molitona** [comment]
> Contributions are always welcomed, unfortunately even if I could work on SkyTube 8 hours a day for the next months, I couldn't implement all the feature requests alone, to address the 138 open issue in this tracker.

We really need that feature It's mandatory to use the app, please.

**Comment by SebbeM** [comment]
I'm looking into this. Parsing JSON should be pretty simple. I'm keeping the XML parsing as well so people with old exports can still use them.

**Comment by SebbeM** [comment]
This is now fixed in PR #878. Please have a look and see what I messed up.

**Comment by gzsombor** [comment]
@SebbeM implementation has been merged

**Comment by thecountoftuscany** [comment]
It seems like Google may have yet again changed their export format: the takeout now gives only a CSV file instead of JSON. The fields in the CSV are: `Channel Id,Channel Url,Channel Title`.

**Comment by SebbeM** [comment]
I can take a look at it but it should probably be treated as a separate issue.
