### ISSUE TITLE
Format Import Youtube Subscriptions XML

### ISSUE THREAD

**Issue by dmorady1** [ram-on/SkyTube#839]
Hello, 

can you please give me an example XML in which the youtube subscriptions 
needs to be in, to import them. 
Is it necessary that the file of the XML has a specific name? 

Thank you very much.

**Comment by gzsombor** [comment]
Good question, I don't know the exact format, I could try to decrypt the code, which implements the parsing - the actual code is [here](https://github.com/ram-on/SkyTube/blob/master/app/src/main/java/free/rm/skytube/gui/businessobjects/SubscriptionsBackupsManager.java#L235).

If I understand correctly, it needs _outline_ tags, with an _xmlUrl_ attribute, which contains the channel URL the regexp pattern used searches for 'channel_id=(....)' and the _title_ atttribute.
So something like
```
 <document>
  <outline xmlUrl="....channel_id=UCuAXFkgsw1L7xaCfnd5JJOw" title="Something" />
 </document>
```
could work, but I haven't tried it.

**Comment by dmorady1** [comment]
Okay thank you very much.
