### ISSUE TITLE
[Request]Watch videos in an external video player

### ISSUE THREAD

**Issue by kilroy01** [ram-on/SkyTube#84]
A way to watch videos in an external video player, like MX Player would be amazing. Also, i imagine if i uninstall the app, i lose the subscriptions, so a way to create an account or something to save them would be very useful. Let me know if i can helf you with translations.

**Comment by ram-on** [comment]
Regarding the MX Player:  have you tried to watch the video using SkyTube and then (from the menu) click on "Open With"?

Regarding the subscriptions:  I agree.  I will introduce an export/import subscriptions functionality.  #27 & #52

Regarding translations:  Yes pls - any help is appreciated.  Currently the app is translated in English, Spanish, Hungarian, Polish and German.  What languages are you fluent in?

**Comment by kilroy01** [comment]
When i click on "Open With" it opens the video with the official Youtube app, i'll mess around with it a bit more, maybe i get it to work. 
I'm fluent in Romanian. If you want to, you could set up a project on Zanata (translate.zanata.org) so it would be easier for people to translate.

**Comment by ram-on** [comment]
I'm closing this ticket due to lack of feedback.  Regarding translations, I am trying to get an account with Weblate.
