### ISSUE TITLE
[Bug] An error has occurred while getting subscribed channels.

### ISSUE THREAD

**Issue by github-throwaway** [ram-on/SkyTube#85]
The newest version of SkyTube has no content what so ever. 
I get an error message (see screenshot) but other than that the app remains empty. So even if you search for stuff nothing shows up. 

![screenshot_2017-02-26-02-49-02](https://cloud.githubusercontent.com/assets/25488086/23336412/de898266-fbcf-11e6-9d4f-0affdcf54b13.png)
 

**N9005 | Android 5.0 | SkyTube 2.3**

**Comment by SpotComms** [comment]
Its not a bug, the API key used has hit its quota, that or Google disabled it. It's something @ram-on will have to check.

**Comment by MadMaverick9** [comment]
This is bad.

Interestingly when I searched for "pull the rug from under you" on ddg, the second link was: https://www.reddit.com/r/programming/comments/5mwkbz/using_google_apis_is_as_stupid_as_ever_theyll/

> Using Google API's is as stupid as ever. They'll eventually pull the rug from under you.

Whilst I much appreciate the work you are doing - I really like SkyTube, because it is better than the default youtube application - developing for a platform that you do not control seems a bad idea.

This may eventually affect applications like SMTube as well.

**Comment by xamica** [comment]
Confirm problem with key.

But applications like youtube-dl will never affected by this problem, as here no keys at all.

Backtrace:
```
E/YouTubeChannel( 2018): Error has occurred while getting Featured Videos. 
E/YouTubeChannel( 2018): com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
E/YouTubeChannel( 2018): {
E/YouTubeChannel( 2018): "code": 403,
E/YouTubeChannel( 2018): "errors": [
E/YouTubeChannel( 2018): {
E/YouTubeChannel( 2018): "domain": "usageLimits",
E/YouTubeChannel( 2018): "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube/quotas?project=102659752285",
E/YouTubeChannel( 2018): "reason": "dailyLimitExceeded",
E/YouTubeChannel( 2018): "extendedHelp": "https://console.developers.google.com/apis/api/youtube/quotas?project=102659752285"
E/YouTubeChannel( 2018): }
E/YouTubeChannel( 2018): ],
E/YouTubeChannel( 2018): "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube/quotas?project=102659752285"
E/YouTubeChannel( 2018): }
E/YouTubeChannel( 2018): at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
E/YouTubeChannel( 2018): at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
E/YouTubeChannel( 2018): at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
E/YouTubeChannel( 2018): at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
E/YouTubeChannel( 2018): at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419) 
E/YouTubeChannel( 2018): at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
E/YouTubeChannel( 2018): at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
E/YouTubeChannel( 2018): at free.rm.skytube.businessobjects.YouTubeChannel.getChannelInfo(YouTubeChannel.java:118)
E/YouTubeChannel( 2018): at free.rm.skytube.businessobjects.YouTubeChannel.init(YouTubeChannel.java:90)
E/YouTubeChannel( 2018): at free.rm.skytube.businessobjects.db.SubscriptionsDb.getSubscribedChannels(SubscriptionsDb.java:149)
E/YouTubeChannel( 2018): at free.rm.skytube.businessobjects.db.SubscriptionsDb.getSubscribedChannels(SubscriptionsDb.java:126)
E/YouTubeChannel( 2018): at free.rm.skytube.businessobjects.db.GetSubscribedChannelsTask.doInBackground(GetSubscribedChannelsTask.java:61)
E/YouTubeChannel( 2018): at free.rm.skytube.businessobjects.db.GetSubscribedChannelsTask.doInBackground(GetSubscribedChannelsTask.java:35)
E/YouTubeChannel( 2018): at android.os.AsyncTask$2.call(AsyncTask.java:288)

```

**Comment by ram-on** [comment]
On the 24th, 25th and 26th Feb, SkyTube reached the daily quota of 1,000,000 queries.  The only solution for now is to have 2 different API keys, both owned by 2 different persons.

For the future, I would like the app to become less dependent to the YouTube API.

**Comment by SpotComms** [comment]
@ram-on Wouldn't changing the subscriptions list to only refresh manually help? Along with adding options for the user to disable the currently featured/popular pages.

You could also add an option for the user to input their own API key, like how Kodi's YouTube app does. And you can add a fallback scraper option once it is the quote is hit (granted its a *lot* of work).

**Comment by ram-on** [comment]
> You could also add an option for the user to input their own API key

I like that idea - will be implemented for sure.

**Comment by atomjack** [comment]
@ram-on I just made a PR that adds a Preference for the user to enter their own YouTube Data API key, please check it out! When you hit ok after entering(pasting) the API key, it attempts to do a simple call using the entered key (basically gets one featured video), to make sure it's a valid key. If it's invalid, it resets it back to null.

**Comment by ram-on** [comment]
Resolved.  Refer to c92616cc61797be1aaa53c0fd00732b2607ef945.
