### ISSUE TITLE
[Bug] No notifications despite new videos on channels

### ISSUE THREAD

**Issue by github-throwaway** [ram-on/SkyTube#86]
Since SkyTube 2.3 I'm missing the red dot in the subscriptions drawer when a channels uploads a new video. This affects all channels.

Is anyone else experiencing this issue? 

**N9005 | Android 5.0 | SkyTube 2.3**

**Comment by xamica** [comment]
Me too

**Comment by Dazrok** [comment]
same here

**Comment by ram-on** [comment]
Fixed.  Refer to 8d0dd552b9c6bb014fd8031c5e7bcf687a64ece2.
