### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [ram-on/SkyTube#867]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the Mostpupolar page, the text overlap each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165857-dbaf8580-4857-11eb-9e22-120ae1901389.png)
App version is 2.975, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
<img width="443" alt="bug-skytube oos" src="https://user-images.githubusercontent.com/18572115/103167103-2682ca80-4863-11eb-9fbd-13e04f4c796f.png">

**Comment by gzsombor** [comment]
I guess, no one has ever tried this - unfortunately setting layout to handle every possible case is not simple, I haven't even know that you can configure font sizes in Android, independently from your screen resolution
