### ISSUE TITLE
Videos stop playing after 6 minutes

### ISSUE THREAD

**Issue by Zebouski** [ram-on/SkyTube#87]
Title says it all. Every video will do this, full stop after about 6 minutes and the play/pause cease to work. Pressing the back-5s button restarts the video but having to do this every 6 minutes can get very annoying on long videos.

NewPipe has the same exact problem, which makes sense since it seems both use the what looks like the same video player.

Using CyanogenMod 13
Android 6.0.1
Have not tested on any other devices

**Comment by ram-on** [comment]
@Zebouski I cannot replicate this problem.  Used multiple devices.
