### ISSUE TITLE
Instructions for exporting subscriptions are wrong

### ISSUE THREAD

**Issue by SebbeM** [ram-on/SkyTube#882]
The instructions on how to export subscriptions from Youtube are no longer correct. The link provided is also wrong.

**Comment by gzsombor** [comment]
Yes, you are right, obviously. Could you please provide a better explanation?

**Comment by SebbeM** [comment]
Absolutely. Just wanted to confirm that this is wrong before I dove into it. Should this be done as a regular PR or should I do it through Weblate?

**Comment by gzsombor** [comment]
I think, it's better to have a regular PR. I'm not sure, that you can edit the English labels through Weblate - it wouldn't make to much sense.

**Comment by gzsombor** [comment]
Fix merged!
