### ISSUE TITLE
Crash on selecting video.

### ISSUE THREAD

**Issue by blitztide** [ram-on/SkyTube#885]
SkyTube crashes on selecting certain videos:
Error log:
`01-11 12:58:29.903 20410 20410 D AndroidRuntime: Shutting down VM
01-11 12:58:29.906 20410 20410 E AndroidRuntime: FATAL EXCEPTION: main
01-11 12:58:29.906 20410 20410 E AndroidRuntime: Process: free.rm.skytube.extra, PID: 20410
01-11 12:58:29.906 20410 20410 E AndroidRuntime: java.lang.NumberFormatException: For input string: "2160p6"
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at java.lang.Integer.parseInt(Integer.java:615)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at java.lang.Integer.parseInt(Integer.java:650)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at free.rm.skytube.businessobjects.YouTube.VideoStream.VideoResolution.resolutionToVideoResolution(VideoResolution.java:99)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at free.rm.skytube.app.StreamSelectionPolicy$VideoStreamWithResolution.<init>(StreamSelectionPolicy.java:164)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at free.rm.skytube.app.StreamSelectionPolicy.pick(StreamSelectionPolicy.java:127)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at free.rm.skytube.app.StreamSelectionPolicy.pickVideo(StreamSelectionPolicy.java:116)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at free.rm.skytube.app.StreamSelectionPolicy.select(StreamSelectionPolicy.java:51)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at free.rm.skytube.gui.fragments.YouTubePlayerV2Fragment$2.onGetDesiredStream(YouTubePlayerV2Fragment.java:466)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at free.rm.skytube.businessobjects.YouTube.Tasks.GetVideoStreamTask.onPostExecute(GetVideoStreamTask.java:67)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at free.rm.skytube.businessobjects.YouTube.Tasks.GetVideoStreamTask.onPostExecute(GetVideoStreamTask.java:35)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:755)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at android.os.AsyncTask.access$900(AsyncTask.java:192)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-11 12:58:29.906 20410 20410 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
`

Device: Xiaomi Redmi6A
Android: 10
LineageOS 17.1-20200727-UNOFFICIAL-cactus
No Google Apps installed
SkyTube Version: 2.976 Extra (2021-01-05 21:46)

Video Link to crash:
https://youtu.be/p6q54q2iam8

**Comment by drogga** [comment]
I think you need to adjust the new rez. settings, because it seems to me by the log that it tries to play in 2160p at 60 FPS, it might be fixed in 2.977 (you can try the debug build of it, it was suggested to me in another recent issue), or I might be wrong, because I can't exactly "read"\understand crash logs...

**Comment by blitztide** [comment]
The issue persists even after setting the Max resolution to 2160p, there isn't a setting to adjust for fps.

**Comment by gzsombor** [comment]
Thanks for the detailed crash report, fortunately it's already fixed in [this commit](https://github.com/ram-on/SkyTube/commit/27078368e4ff37f2245efd52f606c97b6249c67e)
