### ISSUE TITLE
[FR] making this app like Zing Youtube? (adding its features)

### ISSUE THREAD

**Issue by husadd** [ram-on/SkyTube#9]
Before anything, yes it follows the TOS of Youtube API (or whatever it's called)! And it doesn't need logging in to have the features I wrote below.

I've been using Zing Youtube for around a 
year and I love every feature it has, but as I see it is not supported by developers anymore and has an old bad appearence and design with an amazing performence (and missing some features).

I wish Skytube will have Zing's features like: search history, watch history, add videos to favorite, add channels to favorites, queue videos, browsing (searching for videos and viewing comments..etc) while the video is playing in a fixed position at the top, sort by views or date or revelence..
Also there are some small features that will make the app better and sadly not present in Zing like: viewing likes and dislikes, viewing replies on comments and subscribers...

Thanks :) :)

**Comment by gzsombor** [comment]
I think, SkyTube has most of the listed features, so we can close this issue - if something is missing, please open a separate one.
