### ISSUE TITLE
[Request] Add volume control

### ISSUE THREAD

**Issue by xamica** [ram-on/SkyTube#92]
I want to control volume of a clips in the player, not in whole system.
Usually I have some other apps with sound, running in background, adjusted to comfortable volume level. And when I see any clips on youtube, I forced change sound level everywhere: in system, in background apps. But wait, why not to control it in player?

If you can gain volume, like 200% in VLC, it can be a lot better.

**Comment by ram-on** [comment]
Hi @xamica.  This feature has been implemented and will be available in the next release.
