### ISSUE TITLE
Playing in background mode stops working after a drew minutes

### ISSUE THREAD

**Issue by daleylife411** [ram-on/SkyTube#96]
I have a galaxy s7 and previously, background mode worked perfectly unless I was in power save mode.

But now, with Nougat, no matter what mode the phone is in, background mode doesn't always work.

**Comment by ram-on** [comment]
SkyTube never officially supported background play.  I'm surprised that it worked on S7.

**Comment by daleylife411** [comment]
Yes, as long as I wasn't in power saving mode, background Mode worked flawlessly. But gauging by your reply it doesn't look like you're actively going to be supporting that? That's really a shame because I was using skytube to listen to music.

**Comment by ram-on** [comment]
@daleylife411 Proper background will be added in the future.  Refer to #6.
